### ISSUE TITLE
Problems with <list>

### ISSUE THREAD

**Issue by jl-rey** [dotnet/docfx#6687] opened 2020-10-24 14:48 UTC
I am using Windows, VS 16.7.6,  DocFx: v2.56.4

The case of  `<list><item>content</item></list>` has no comment only the bullet.

This occurs for both the bullet and numeric lists.

### Example Code
See the following example that was added to your seed example DotnetNew project Class1.cs.

``` c#
namespace DotnetNew
{

    /// <summary>
    ///   <para>Class1 is used to experiment with DocFx formatting.</para>
    /// </summary>
    public class Class1
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Class1" /> class.
        /// </summary>
        public Class1()
        {

        }

        /// <summary>
        ///   <para>Lists the method.</para>
        ///   <para>A bullet list</para>
        ///   <list type="bullet">
        ///     <item>Bullet 1</item>
        ///     <item>Bullet 2</item>
        ///     <item>Bullet 3</item>
        ///   </list>
        ///   <para>A numbered list</para>
        ///   <list type="number">
        ///     <item>One</item>
        ///     <item>Two</item>
        ///     <item>Three</item>
        ///   </list>
        /// </summary>
        /// <param name="a">a</param>
        /// <param name="b">b</param>
        /// <returns>int always 0</returns>
        public int ListMethod(int a, string b)
        {
            return 0;
        }
    }
}

```

The <List> tags did not have any content.

### Expected Result
I **expected** a result something like this for the lists. (simulated in Markdown.)

> Lists the Methods
>
> A Bullet List
>
>- Bullet 1
>- Bullet 2
>- Bullet 3
>
>A numeric List
>
>1. One
>2. Two
>3. Three

Expected HTML (Edited)

``` Html
<div class="markdown level1 summary"><p>Lists the method.</p>
<p>A bullet list</p>
<ul><li>Bullet 1</li><li>Bullet 2</li><li>Bullet 3</li></ul>
<p>A numbered list</p>
<ol><li>One</li><li>Two</li><li>Three</li></ol>
</div>
``` 

### Actual Result
Actual Html Output

``` HTML
<div class="markdown level1 summary"><p>Lists the method.</p>
<p>A bullet list</p>
<ul><li></li><li></li><li></li></ul>
<p>A numbered list</p>
<ol><li></li><li></li><li></li></ol>
</div>
```

### Conclusion

Unless there is some kind of a switch that I missed that changes this behavior it seems broken to me.

Help me if I missed something.

**Comment by KalleOlaviNiemitalo** [comment] 2020-10-28 17:24
This looks like a duplicate of <https://github.com/dotnet/docfx/issues/5343>. I believe `<item><description>Item 1</description></item>` will work.

**Comment by jl-rey** [comment] 2020-10-30 13:14
Adding the description to this did work.

Thanks

**Comment by craigfowler** [comment] 2021-01-05 20:08
Propose closing this issue as a dupe?  We've got confirmation that the same workaround worked OK.

**Closed** 2021-01-09 16:11 UTC
