### ISSUE TITLE
Sample project API Documentation fails when output path (-o) is set

### ISSUE THREAD

**Issue by arlosi** [dotnet/docfx#1890] opened 2017-07-18 20:41 UTC
**DocFX Version Used**: docfx 2.20.0.0

**Steps to Reproduce**:

1. Clone sample repo: <https://github.com/docascode/docfx-seed> (make sure it's clean)
2. Run `docfx -o <an alternative directory> --serve`
3. Attempt to view "API Documentation" on the site.

**Expected Behavior**:
API documentation should appear.

**Actual Behavior**:
Page not found. 

If I remove the `-o` parameter, it works fine. I'm attempting to cause the documentation to be placed in my project's Binaries directory rather than the `_site` folder adjacent to the `docfx.json`.

The following warning appears in the logs:
`Warning:[BuildCommand.Build Document.CompilePhaseHandlerWithIncremental.TocDocumentProcessor.Prebuild.BuildTocDocument](toc.yml)Unable to find either toc.yml or toc.md inside obj/api/. Make sure the file is included in config file docfx.json!`

How does the `build` step reference path of the generated API documentation, when it's generated into a alternative directory?

**Comment by vicancy** [comment] 2017-07-19 02:57
The issue is that `docfx metadata` uses `alternative directory` for output, however `docfx build` relies on output of `docfx metadata` as input, it is a design bug in docfx when `metadata` and `build` are running sequentially in one command `docfx`.

To workaround this issue, you can call `docfx metadata` and `docfx build -o <directory> --serve` separately.

**Comment by yufeih** [comment] 2023-11-29 06:50
Fixed with the new `output` JSON config over `dest`.

**Closed by yufeih** 2023-11-29 06:50 UTC
Labels: bug, dotnet
