### ISSUE TITLE
metadata filter causes AggregateException

### ISSUE THREAD

**Issue by Eonasdan** [dotnet/docfx#277] opened 2016-04-25 19:28 UTC
Using the [`"filter": "filterConfig.yml"`](http://dotnet.github.io/docfx/tutorial/howto_filter_out_unwanted_apis.html) results in a `AggregateException` being thrown.
### Minimal repro steps
1. Edit `docfx.json` to include `"filter": "filterConfig.yml"`
2. Create filterConfig.yml
3. Add filter item(s)
4. Run/Build project with msbuild nuget package
5. Project fails to build
### Expected result

Api to generate excluding matching items
### Actual result

Three errors are shown.

If the filter line is removed from the config, the project builds as expected.
### Further technical details

Error Messages:

```
Error: System.AggregateException: One or more errors occurred. ---> Microsoft.DocAsCode.Exceptions.ExtractMetadataException: Error extracting metadata for {"Items":{"obj/api":["C:/projects/PROJECT/tfs/PROJECT.NET/PROJECT/jonathan/PROJECT/PROJECT.sln"]},"ApiFolderName":"","TocFileName":"toc.yml","IndexFileName":".manifest","PreserveRawInlineComments":false,"ForceRebuild":false,"FilterConfigFile":"filterConfig.yml"}: System.NullReferenceException: Object reference not set to an instance of an object.
Error: System.AggregateException: One or more errors occurred. ---> Microsoft.DocAsCode.Exceptions.ExtractMetadataException: Error extracting metadata for {"Items":{"obj/api":["C:/projects/PROJECT/tfs/PROJECT.NET/PROJECT/jonathan/PROJECT/PROJECT.sln"]},"ApiFolderName":"","TocFileName":"toc.yml","IndexFileName":".manifest","PreserveRawInlineComments":false,"ForceRebuild":false,"FilterConfigFile":"filterConfig.yml"}: System.NullReferenceException: Object reference not set to an instance of an object.
Error MSB3073: The command ""C:\projects\PROJECT\tfs\PROJECT.NET\Internal\Production\Docs\packages\docfx.msbuild.1.7.2\build\..\tools\docfx.exe" "C:\projects\PROJECT\tfs\PROJECT.NET\Internal\Production\Docs\Docs/docfx.json" -o "" -l "log.txt" --logLevel "Verbose"" exited with code 1. (1, 1)
```

filterConfig.yml:

```
apiRules:
-exclude:
    uidRegex: ^PROJECT\.Data\.Migrations.*$
    type: Namespace
-exclude:
    uidRegex: ^PROJECT\.Data\.Repositories.*$
    type: Namespace
```

solution directory:
![image](https://cloud.githubusercontent.com/assets/1006516/14796208/2eef4a5a-0afa-11e6-8eb7-c8a36217b126.png)

**Comment by vwxyzh** [comment] 2016-04-26 03:40
I think we have found this issue, and it should be fixed in v1.8.
It caused by some EII member (Explicit Interface Implementation).
Here is the fix: cf0ae151ae3fcb8f553a02a1cbbe848c3b47d3de

**Comment by Eonasdan** [comment] 2016-05-16 15:32
I just updated my project to 1.9 and it still fails.

Log:
```
{"message":"Config file \"C:\\projects\\PROJECT\\tfs\\PROJECT.NET\\Internal\\Production\\Docs\\Docs/docfx.json\" is used.","date_time":"2016-05-16T15:29:07.6848228Z","message_severity":"verbose"}
{"message":"Completed executing in 5323.221 milliseconds.","date_time":"2016-05-16T15:29:13.1567269Z","message_severity":"info"}
{"message":"System.AggregateException: One or more errors occurred. ---> Microsoft.DocAsCode.Exceptions.ExtractMetadataException: Error extracting metadata for {\"Items\":{\"obj/api\":[\"C:/projects/PROJECT/tfs/PROJECT.NET/PROJECT/jonathan/PROJECT/PROJECT.sln\"]},\"ApiFolderName\":\"\",\"TocFileName\":\"toc.yml\",\"IndexFileName\":\".manifest\",\"PreserveRawInlineComments\":false,\"ForceRebuild\":false,\"FilterConfigFile\":\"filterConfig.yml\"}: System.NullReferenceException: Object reference not set to an instance of an object.\r\n   at Microsoft.DocAsCode.Metadata.ManagedReference.ConfigFilterVisitor.CanVisitCore(IEnumerable`1 ruleItems, ISymbol symbol, Boolean wantProtectedMember, IFilterVisitor outer)\r\n   at Microsoft.DocAsCode.Metadata.ManagedReference.ConfigFilterVisitor.CanVisitApiCore(ISymbol symbol, Boolean wantProtectedMember, IFilterVisitor outer)\r\n   at Microsoft.DocAsCode.Metadata.ManagedReference.CachedFilterVisitor.CanVisitApiCore(ISymbol symbol, Boolean wantProtectedMember, IFilterVisitor outer)\r\n   at Microsoft.DocAsCode.Metadata.ManagedReference.ConfigFilterVisitor.CanVisitCore(IEnumerable`1 ruleItems, ISymbol symbol, Boolean wantProtectedMember, IFilterVisitor outer)\r\n   at Microsoft.DocAsCode.Metadata.ManagedReference.ConfigFilterVisitor.CanVisitApiCore(ISymbol symbol, Boolean wantProtectedMember, IFilterVisitor outer)\r\n   at Microsoft.DocAsCode.Metadata.ManagedReference.CachedFilterVisitor.CanVisitApiCore(ISymbol symbol, Boolean wantProtectedMember, IFilterVisitor outer)\r\n   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)\r\n   at Microsoft.DocAsCode.Metadata.ManagedReference.SymbolVisitorAdapter.VisitDescendants[T](IEnumerable`1 children, Func`2 getChildren, Func`2 filter)\r\n   at Microsoft.DocAsCode.Metadata.ManagedReference.SymbolVisitorAdapter.VisitAssembly(IAssemblySymbol symbol)\r\n   at Microsoft.DocAsCode.Metadata.ManagedReference.ExtractMetadataWorker.<GetMetadataFromProjectLevelCacheAsync>d__29`1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)\r\n   at Microsoft.DocAsCode.Metadata.ManagedReference.ExtractMetadataWorker.<SaveAllMembersFromCacheAsync>d__25.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.DocAsCode.Metadata.ManagedReference.ExtractMetadataWorker.<ExtractMetadataAsync>d__15.MoveNext() ---> System.NullReferenceException: Object reference not set to an instance of an object.\r\n   at Microsoft.DocAsCode.Metadata.ManagedReference.ConfigFilterVisitor.CanVisitCore(IEnumerable`1 ruleItems, ISymbol symbol, Boolean wantProtectedMember, IFilterVisitor outer)\r\n   at Microsoft.DocAsCode.Metadata.ManagedReference.ConfigFilterVisitor.CanVisitApiCore(ISymbol symbol, Boolean wantProtectedMember, IFilterVisitor outer)\r\n   at Microsoft.DocAsCode.Metadata.ManagedReference.CachedFilterVisitor.CanVisitApiCore(ISymbol symbol, Boolean wantProtectedMember, IFilterVisitor outer)\r\n   at Microsoft.DocAsCode.Metadata.ManagedReference.ConfigFilterVisitor.CanVisitCore(IEnumerable`1 ruleItems, ISymbol symbol, Boolean wantProtectedMember, IFilterVisitor outer)\r\n   at Microsoft.DocAsCode.Metadata.ManagedReference.ConfigFilterVisitor.CanVisitApiCore(ISymbol symbol, Boolean wantProtectedMember, IFilterVisitor outer)\r\n   at Microsoft.DocAsCode.Metadata.ManagedReference.CachedFilterVisitor.CanVisitApiCore(ISymbol symbol, Boolean wantProtectedMember, IFilterVisitor outer)\r\n   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)\r\n   at Microsoft.DocAsCode.Metadata.ManagedReference.SymbolVisitorAdapter.VisitDescendants[T](IEnumerable`1 children, Func`2 getChildren, Func`2 filter)\r\n   at Microsoft.DocAsCode.Metadata.ManagedReference.SymbolVisitorAdapter.VisitAssembly(IAssemblySymbol symbol)\r\n   at Microsoft.DocAsCode.Metadata.ManagedReference.ExtractMetadataWorker.<GetMetadataFromProjectLevelCacheAsync>d__29`1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)\r\n   at Microsoft.DocAsCode.Metadata.ManagedReference.ExtractMetadataWorker.<SaveAllMembersFromCacheAsync>d__25.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.DocAsCode.Metadata.ManagedReference.ExtractMetadataWorker.<ExtractMetadataAsync>d__15.MoveNext()\r\n   --- End of inner exception stack trace ---\r\n   at Microsoft.DocAsCode.Metadata.ManagedReference.ExtractMetadataWorker.<ExtractMetadataAsync>d__15.MoveNext()\r\n   --- End of inner exception stack trace ---\r\n   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)\r\n   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)\r\n   at Microsoft.DocAsCode.SubCommands.MetadataCommand.Exec(SubCommandRunningContext context)\r\n   at Microsoft.DocAsCode.SubCommands.CompositeCommand.Exec(SubCommandRunningContext context)\r\n   at Microsoft.DocAsCode.Program.ExecSubCommand(String[] args)\r\n---> (Inner Exception #0) Microsoft.DocAsCode.Exceptions.ExtractMetadataException: Error extracting metadata for {\"Items\":{\"obj/api\":[\"C:/projects/PROJECT/tfs/PROJECT.NET/PROJECT/jonathan/PROJECT/PROJECT.sln\"]},\"ApiFolderName\":\"\",\"TocFileName\":\"toc.yml\",\"IndexFileName\":\".manifest\",\"PreserveRawInlineComments\":false,\"ForceRebuild\":false,\"FilterConfigFile\":\"filterConfig.yml\"}: System.NullReferenceException: Object reference not set to an instance of an object.\r\n   at Microsoft.DocAsCode.Metadata.ManagedReference.ConfigFilterVisitor.CanVisitCore(IEnumerable`1 ruleItems, ISymbol symbol, Boolean wantProtectedMember, IFilterVisitor outer)\r\n   at Microsoft.DocAsCode.Metadata.ManagedReference.ConfigFilterVisitor.CanVisitApiCore(ISymbol symbol, Boolean wantProtectedMember, IFilterVisitor outer)\r\n   at Microsoft.DocAsCode.Metadata.ManagedReference.CachedFilterVisitor.CanVisitApiCore(ISymbol symbol, Boolean wantProtectedMember, IFilterVisitor outer)\r\n   at Microsoft.DocAsCode.Metadata.ManagedReference.ConfigFilterVisitor.CanVisitCore(IEnumerable`1 ruleItems, ISymbol symbol, Boolean wantProtectedMember, IFilterVisitor outer)\r\n   at Microsoft.DocAsCode.Metadata.ManagedReference.ConfigFilterVisitor.CanVisitApiCore(ISymbol symbol, Boolean wantProtectedMember, IFilterVisitor outer)\r\n   at Microsoft.DocAsCode.Metadata.ManagedReference.CachedFilterVisitor.CanVisitApiCore(ISymbol symbol, Boolean wantProtectedMember, IFilterVisitor outer)\r\n   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)\r\n   at Microsoft.DocAsCode.Metadata.ManagedReference.SymbolVisitorAdapter.VisitDescendants[T](IEnumerable`1 children, Func`2 getChildren, Func`2 filter)\r\n   at Microsoft.DocAsCode.Metadata.ManagedReference.SymbolVisitorAdapter.VisitAssembly(IAssemblySymbol symbol)\r\n   at Microsoft.DocAsCode.Metadata.ManagedReference.ExtractMetadataWorker.<GetMetadataFromProjectLevelCacheAsync>d__29`1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)\r\n   at Microsoft.DocAsCode.Metadata.ManagedReference.ExtractMetadataWorker.<SaveAllMembersFromCacheAsync>d__25.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.DocAsCode.Metadata.ManagedReference.ExtractMetadataWorker.<ExtractMetadataAsync>d__15.MoveNext() ---> System.NullReferenceException: Object reference not set to an instance of an object.\r\n   at Microsoft.DocAsCode.Metadata.ManagedReference.ConfigFilterVisitor.CanVisitCore(IEnumerable`1 ruleItems, ISymbol symbol, Boolean wantProtectedMember, IFilterVisitor outer)\r\n   at Microsoft.DocAsCode.Metadata.ManagedReference.ConfigFilterVisitor.CanVisitApiCore(ISymbol symbol, Boolean wantProtectedMember, IFilterVisitor outer)\r\n   at Microsoft.DocAsCode.Metadata.ManagedReference.CachedFilterVisitor.CanVisitApiCore(ISymbol symbol, Boolean wantProtectedMember, IFilterVisitor outer)\r\n   at Microsoft.DocAsCode.Metadata.ManagedReference.ConfigFilterVisitor.CanVisitCore(IEnumerable`1 ruleItems, ISymbol symbol, Boolean wantProtectedMember, IFilterVisitor outer)\r\n   at Microsoft.DocAsCode.Metadata.ManagedReference.ConfigFilterVisitor.CanVisitApiCore(ISymbol symbol, Boolean wantProtectedMember, IFilterVisitor outer)\r\n   at Microsoft.DocAsCode.Metadata.ManagedReference.CachedFilterVisitor.CanVisitApiCore(ISymbol symbol, Boolean wantProtectedMember, IFilterVisitor outer)\r\n   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)\r\n   at Microsoft.DocAsCode.Metadata.ManagedReference.SymbolVisitorAdapter.VisitDescendants[T](IEnumerable`1 children, Func`2 getChildren, Func`2 filter)\r\n   at Microsoft.DocAsCode.Metadata.ManagedReference.SymbolVisitorAdapter.VisitAssembly(IAssemblySymbol symbol)\r\n   at Microsoft.DocAsCode.Metadata.ManagedReference.ExtractMetadataWorker.<GetMetadataFromProjectLevelCacheAsync>d__29`1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)\r\n   at Microsoft.DocAsCode.Metadata.ManagedReference.ExtractMetadataWorker.<SaveAllMembersFromCacheAsync>d__25.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.DocAsCode.Metadata.ManagedReference.ExtractMetadataWorker.<ExtractMetadataAsync>d__15.MoveNext()\r\n   --- End of inner exception stack trace ---\r\n   at Microsoft.DocAsCode.Metadata.ManagedReference.ExtractMetadataWorker.<ExtractMetadataAsync>d__15.MoveNext()<---\r\n","date_time":"2016-05-16T15:29:13.160186Z","message_severity":"error"}
```

**Comment by vwxyzh** [comment] 2016-05-17 03:55
@Eonasdan can you provide some project for repro this bug?

**Comment by Eonasdan** [comment] 2016-05-17 13:37
My test project seemed to work without an error but when I use it my client project it fails. The main difference between the two is that the client has docfx in an outside project.

Example:
```
/PATHTO/folder/folder/folder/docs.sln
/PATHTO/other/other/other/project.sln
```

In docs.sln is where the `docfx.json` is and points the `cwd` source to the main projects sln file.

If I change my test project to point to the same `cwd` path the build fails.

I also setup a second test project to verify and that does seem to be the issue. If the `cwd` is pointed to a location outside of project where `docfx.json` lives, the build fails.

I can upload both test projects if needed.

**Comment by grokys** [comment] 2016-08-04 15:00
I'm getting this exception too.

Repro:

1. Check out https://github.com/AvaloniaUI/Avalonia/commit/a4da22ed24c628dad6502029d4f1b84f287abc01
2. Go to docs directory
3. Run docfx (2.2.2 is what I'm using)

**Comment by joszz** [comment] 2016-09-05 14:44
Same here, getting this as well. Would be nice if this was fixed.
Running the 2.4 build

**Comment by sliverninja** [comment] 2017-01-12 18:55
We fixed this by removing duplicate `ProjectReference` elements in the `csproj` - somehow VS IDE allowed us to add duplicate entries or someone had done so manually. DocFX doesn't like when the same project is added more than once as it's building out the metadata  YAML.

**Comment by bentayloruk** [comment] 2017-01-30 15:08
I got the `AggregateException` exception when trying to use a custom filter file too (with `2.11.2.0`).  However, I noticed the inner exception was actually `FileNotFound` on the filter file.  I was using a path relative to the `docs` folder which was wrong, because I was invoking `docfx.exe` from a parent directory.  Once I changed the path it to be relative to the current directory for docfx, it worked fine.  Just adding this here, in case it happens to others and they don't notice the inner exception.

**Comment by vicancy** [comment] 2017-05-09 08:31
Looks like AggregatedException can happen in several cases, things needs to be done:
1. Improve error message to expose more inner exceptions in a better way
2. Looking into the cases

**Comment by Eonasdan** [comment] 2017-06-26 18:20
nearly a year later and I'm trying this out on another project and filter config still causes issues.

filterConfig.yml
```
apiRules:
-exclude:
    uidRegex: ^PROJECT\.DAL\.SQL\.Migrations.*$
    type: Namespace
-exclude:
    uidRegex: ^PROJECT\.DAL\.SQL\.Repositories.*$
    type: Namespace
```

Log:
```
[17-06-26 05:56:36.075]Info:Config file docfx.json found, start generating metadata...
[17-06-26 05:56:44.172]Info:Completed executing in 7838.1972 milliseconds.
[17-06-26 05:56:44.177]Error:System.AggregateException: One or more errors occurred. ---> Microsoft.DocAsCode.Exceptions.ExtractMetadataException: Error extracting metadata for [PATH]/PROJECT.Bootstrapper/PROJECT.Bootstrapper.csproj,[PATH]/PROJECT.Business/PROJECT.Business.csproj,[PATH]/PROJECT.DAL.SQL/PROJECT.DAL.SQL.csproj,[PATH]/PROJECT.Reports/PROJECT.Reports.csproj,[PATH]/PROJECT.Tests/PROJECT.Tests.csproj,[PATH]/PROJECT.Web/PROJECT.Web.csproj,[PATH]/PROJECT.Webservices/PROJECT.Webservices.csproj: Value cannot be null.
Parameter name: first ---> System.ArgumentNullException: Value cannot be null.
Parameter name: first
   at System.Linq.Enumerable.Concat[TSource](IEnumerable`1 first, IEnumerable`1 second)
   at Microsoft.DocAsCode.Metadata.ManagedReference.SymbolVisitorAdapter.MergeConfigRule(ConfigFilterRule defaultRule, ConfigFilterRule userRule)
   at Microsoft.DocAsCode.Metadata.ManagedReference.SymbolVisitorAdapter.LoadConfigFilterRule(String filterConfigFile)
   at Microsoft.DocAsCode.Metadata.ManagedReference.SymbolVisitorAdapter..ctor(YamlModelGenerator generator, SyntaxLanguage language, Compilation compilation, Boolean preserveRawInlineComments, String filterConfigFile, IReadOnlyDictionary`2 extensionMethods)
   at Microsoft.DocAsCode.Metadata.ManagedReference.MetadataExtractor.Extract(ExtractMetadataOptions options)
   at Microsoft.DocAsCode.Metadata.ManagedReference.ExtractMetadataWorker.<GetMetadataFromProjectLevelCacheAsync>d__27`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.DocAsCode.Metadata.ManagedReference.ExtractMetadataWorker.<SaveAllMembersFromCacheAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.DocAsCode.Metadata.ManagedReference.ExtractMetadataWorker.<ExtractMetadataAsync>d__12.MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.DocAsCode.Metadata.ManagedReference.ExtractMetadataWorker.<ExtractMetadataAsync>d__12.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Microsoft.DocAsCode.SubCommands.MetadataCommand.ExecCore()
   at Microsoft.DocAsCode.SubCommands.MetadataCommand.Exec(SubCommandRunningContext context)
   at Microsoft.DocAsCode.Program.ExecSubCommand(String[] args)
---> (Inner Exception #0) Microsoft.DocAsCode.Exceptions.ExtractMetadataException: Error extracting metadata for [PATH]/PROJECT.Bootstrapper/PROJECT.Bootstrapper.csproj,[PATH]/PROJECT.Business/PROJECT.Business.csproj,[PATH]/PROJECT.DAL.SQL/PROJECT.DAL.SQL.csproj,[PATH]/PROJECT.Reports/PROJECT.Reports.csproj,[PATH]/PROJECT.Tests/PROJECT.Tests.csproj,[PATH]/PROJECT.Web/PROJECT.Web.csproj,[PATH]/PROJECT.Webservices/PROJECT.Webservices.csproj: Value cannot be null.
Parameter name: first ---> System.ArgumentNullException: Value cannot be null.
Parameter name: first
   at System.Linq.Enumerable.Concat[TSource](IEnumerable`1 first, IEnumerable`1 second)
   at Microsoft.DocAsCode.Metadata.ManagedReference.SymbolVisitorAdapter.MergeConfigRule(ConfigFilterRule defaultRule, ConfigFilterRule userRule)
   at Microsoft.DocAsCode.Metadata.ManagedReference.SymbolVisitorAdapter.LoadConfigFilterRule(String filterConfigFile)
   at Microsoft.DocAsCode.Metadata.ManagedReference.SymbolVisitorAdapter..ctor(YamlModelGenerator generator, SyntaxLanguage language, Compilation compilation, Boolean preserveRawInlineComments, String filterConfigFile, IReadOnlyDictionary`2 extensionMethods)
   at Microsoft.DocAsCode.Metadata.ManagedReference.MetadataExtractor.Extract(ExtractMetadataOptions options)
   at Microsoft.DocAsCode.Metadata.ManagedReference.ExtractMetadataWorker.<GetMetadataFromProjectLevelCacheAsync>d__27`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.DocAsCode.Metadata.ManagedReference.ExtractMetadataWorker.<SaveAllMembersFromCacheAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.DocAsCode.Metadata.ManagedReference.ExtractMetadataWorker.<ExtractMetadataAsync>d__12.MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.DocAsCode.Metadata.ManagedReference.ExtractMetadataWorker.<ExtractMetadataAsync>d__12.MoveNext()<---



Build failed.
[17-06-26 05:56:44.184]Error:System.AggregateException: One or more errors occurred. ---> Microsoft.DocAsCode.Exceptions.ExtractMetadataException: Error extracting metadata for [PATH]/PROJECT.Bootstrapper/PROJECT.Bootstrapper.csproj,[PATH]/PROJECT.Business/PROJECT.Business.csproj,[PATH]/PROJECT.DAL.SQL/PROJECT.DAL.SQL.csproj,[PATH]/PROJECT.Reports/PROJECT.Reports.csproj,[PATH]/PROJECT.Tests/PROJECT.Tests.csproj,[PATH]/PROJECT.Web/PROJECT.Web.csproj,[PATH]/PROJECT.Webservices/PROJECT.Webservices.csproj: Value cannot be null.
Parameter name: first ---> System.ArgumentNullException: Value cannot be null.
Parameter name: first
   at System.Linq.Enumerable.Concat[TSource](IEnumerable`1 first, IEnumerable`1 second)
   at Microsoft.DocAsCode.Metadata.ManagedReference.SymbolVisitorAdapter.MergeConfigRule(ConfigFilterRule defaultRule, ConfigFilterRule userRule)
   at Microsoft.DocAsCode.Metadata.ManagedReference.SymbolVisitorAdapter.LoadConfigFilterRule(String filterConfigFile)
   at Microsoft.DocAsCode.Metadata.ManagedReference.SymbolVisitorAdapter..ctor(YamlModelGenerator generator, SyntaxLanguage language, Compilation compilation, Boolean preserveRawInlineComments, String filterConfigFile, IReadOnlyDictionary`2 extensionMethods)
   at Microsoft.DocAsCode.Metadata.ManagedReference.MetadataExtractor.Extract(ExtractMetadataOptions options)
   at Microsoft.DocAsCode.Metadata.ManagedReference.ExtractMetadataWorker.<GetMetadataFromProjectLevelCacheAsync>d__27`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.DocAsCode.Metadata.ManagedReference.ExtractMetadataWorker.<SaveAllMembersFromCacheAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.DocAsCode.Metadata.ManagedReference.ExtractMetadataWorker.<ExtractMetadataAsync>d__12.MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.DocAsCode.Metadata.ManagedReference.ExtractMetadataWorker.<ExtractMetadataAsync>d__12.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Microsoft.DocAsCode.SubCommands.MetadataCommand.ExecCore()
   at Microsoft.DocAsCode.SubCommands.MetadataCommand.Exec(SubCommandRunningContext context)
   at Microsoft.DocAsCode.Program.ExecSubCommand(String[] args)
---> (Inner Exception #0) Microsoft.DocAsCode.Exceptions.ExtractMetadataException: Error extracting metadata for [PATH]/PROJECT.Bootstrapper/PROJECT.Bootstrapper.csproj,[PATH]/PROJECT.Business/PROJECT.Business.csproj,[PATH]/PROJECT.DAL.SQL/PROJECT.DAL.SQL.csproj,[PATH]/PROJECT.Reports/PROJECT.Reports.csproj,[PATH]/PROJECT.Tests/PROJECT.Tests.csproj,[PATH]/PROJECT.Web/PROJECT.Web.csproj,[PATH]/PROJECT.Webservices/PROJECT.Webservices.csproj: Value cannot be null.
Parameter name: first ---> System.ArgumentNullException: Value cannot be null.
Parameter name: first
   at System.Linq.Enumerable.Concat[TSource](IEnumerable`1 first, IEnumerable`1 second)
   at Microsoft.DocAsCode.Metadata.ManagedReference.SymbolVisitorAdapter.MergeConfigRule(ConfigFilterRule defaultRule, ConfigFilterRule userRule)
   at Microsoft.DocAsCode.Metadata.ManagedReference.SymbolVisitorAdapter.LoadConfigFilterRule(String filterConfigFile)
   at Microsoft.DocAsCode.Metadata.ManagedReference.SymbolVisitorAdapter..ctor(YamlModelGenerator generator, SyntaxLanguage language, Compilation compilation, Boolean preserveRawInlineComments, String filterConfigFile, IReadOnlyDictionary`2 extensionMethods)
   at Microsoft.DocAsCode.Metadata.ManagedReference.MetadataExtractor.Extract(ExtractMetadataOptions options)
   at Microsoft.DocAsCode.Metadata.ManagedReference.ExtractMetadataWorker.<GetMetadataFromProjectLevelCacheAsync>d__27`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.DocAsCode.Metadata.ManagedReference.ExtractMetadataWorker.<SaveAllMembersFromCacheAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.DocAsCode.Metadata.ManagedReference.ExtractMetadataWorker.<ExtractMetadataAsync>d__12.MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.DocAsCode.Metadata.ManagedReference.ExtractMetadataWorker.<ExtractMetadataAsync>d__12.MoveNext()<---

	0 Warning(s)
	1 Error(s)
```

**Comment by ansyral** [comment] 2017-06-27 06:21
hi @Eonasdan , your yaml config seems missing a space between `-` and `exclude` so ymserializer failed to deserialize it correctly. could you update it to have a try?
```
apiRules:
- exclude:
    uidRegex: ^PROJECT\.DAL\.SQL\.Migrations.*$
    type: Namespace
- exclude:
    uidRegex: ^PROJECT\.DAL\.SQL\.Repositories.*$
    type: Namespace
```

**Comment by Eonasdan** [comment] 2017-06-29 22:58
@ansyral *sigh* yaml. Yup you're right. Thanks

**Closed** 2017-06-30 04:26 UTC
Labels: Area-Build, bug, priority-1

**Comment by Eonasdan** [comment] 2017-06-30 13:19
@ansyral I'm not sure this ticket was ready to be close as I don't know if the original issue(s) have been resolved.
