### ISSUE TITLE
"Improve this Doc" link not including correct Path

### ISSUE THREAD

**Issue by jbramwell** [dotnet/docfx#5068] opened 2019-09-05 17:57 UTC
**Operation System**:  Windows
**DocFX Version Used**: 2.45
**Template used**: Custom ("material") template

I am testing out DocFX for publishing our guidance which is currently stored as markdown files within Azure DevOps. I've enabled the contribution setting so the "Improve this Doc" link shows up at the top of each doc page. However, the generated links look something like this:

https://dev.azure.com/MY_ACCONT/testproject/_git/Guidance?path=**D:/docs/docfx_project/articles/DevOps/Guidance.md**&version=GBmaster&line=1

Notice how the physical folder where the file is stored is being passed in for the _Path_ parameter. I've tried multiple things now but I can't seem to figure out how to get the correct (Azure DevOps) git Path to be set for each link.

What am I missing?

Thanks!

**Comment by jbramwell** [comment] 2019-09-05 18:09
OK. Turns out it is expecting the source to be the entire git folder (I was copying the *.md files to another folder first, which excluded the .git "stuff"). Once I used the Git folder, all works as expected. :-)

**Comment by superyyrrzz** [comment] 2019-09-10 14:40
@jbramwell You are right. I am closing this as the issue is resolved.

**Closed by superyyrrzz** 2019-09-10 14:40 UTC
