### ISSUE TITLE
GetUserProfileByName throwed OperationCanceledException

### ISSUE THREAD

**Issue by mingwli** [dotnet/docfx#3190] opened 2018-08-13 10:43 UTC
OperationCanceledException throwed when building `azure-docs-pr`
Traceback:
```
System.OperationCanceledException: The operation was canceled.
   at System.Net.Http.HttpClient.HandleFinishSendAsyncError(Exception e, CancellationTokenSource cts)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Octokit.Internal.HttpClientAdapter.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in C:\projects\octokit-net\Octokit\Http\HttpClientAdapter.cs:line 184
   at Octokit.Internal.HttpClientAdapter.Send(IRequest request, CancellationToken cancellationToken) in C:\projects\octokit-net\Octokit\Http\HttpClientAdapter.cs:line 51
   at Octokit.Connection.RunRequest(IRequest request, CancellationToken cancellationToken) in C:\projects\octokit-net\Octokit\Http\Connection.cs:line 635
   at Octokit.Connection.Run[T](IRequest request, CancellationToken cancellationToken) in C:\projects\octokit-net\Octokit\Http\Connection.cs:line 626
   at Octokit.ApiConnection.Get[T](Uri uri, IDictionary`2 parameters)
   at Microsoft.Docs.Build.GitHubAccessor.GetUserProfileByName(String name) in D:\workspace\DocFXRelated\docfx\src\docfx\lib\github\GitHubAccessor.cs:line 39
````

Related docs:
 * [octokit/user-content-get-some-data](https://github.com/octokit/octokit.net/blob/master/docs/getting-started.md#user-content-get-some-data)
 * [github-api/possible-github-api-called](https://developer.github.com/v3/search/#search-users)

FYI @superyyrrzz @928PJY

**Comment by superyyrrzz** [comment] 2018-08-13 15:16
I suspect the operation doesn't support run in parallel when building many documents at the same time. Need some investigation on this.

**Comment by live1206** [comment] 2018-08-14 02:09
https://github.com/dotnet/corefx/blob/fdec34a223b4a3676a781239748776e9332bee43/src/System.Net.Http/src/System/Net/Http/HttpClient.cs#L436
Seems like there is a timeout during the call, we should handle this OperationCanceledException in GetUserProfileByName as well

**Comment by yufeih** [comment] 2018-08-14 07:33
`HttpClient`, `Octokit` is thread safe, the cache in [UserProfileCache](https://github.com/dotnet/docfx/blob/v3/src/docfx/lib/github/UserProfileCache.cs#L31) is not atomic, we maybe calling GitHub for the same user many times

**Comment by yufeih** [comment] 2018-08-15 01:59
@superyyrrzz test now runs significantly slower (almost 2 minutes), I suspect it is because we currently don't write back to on disk user profile.

**Comment by superyyrrzz** [comment] 2018-09-30 09:56
Seems GitHub doesn't welcome concurrent call: https://developer.github.com/v3/guides/best-practices-for-integrators/#dealing-with-abuse-rate-limits

**Comment by OsmondJiang** [comment] 2018-11-14 02:55
i met that issue again during build azure-docs-pr.ja-jp, so re-open it again

**Comment by OsmondJiang** [comment] 2018-11-14 02:55
```
github-api-failed articles/virtual-machine-scale-sets/scripts/cli-sample-single-availability-zone-scale-set.md(0,0): Failed calling GitHub API '': The operation was canceled.
github-api-failed articles/virtual-machine-scale-sets/scripts/powershell-sample-create-complete-scale-set.md(0,0): Failed calling GitHub API '': The operation was canceled.
github-api-failed articles/virtual-machines/scripts/virtual-machines-linux-cli-sample-create-vm-nginx.md(0,0): Failed calling GitHub API '': The operation was canceled.
github-api-failed articles/virtual-machines/scripts/virtual-machines-linux-cli-sample-create-vm-nsg.md(0,0): Failed calling GitHub API '': The operation was canceled.
github-api-failed articles/virtual-machines/scripts/virtual-machines-linux-powershell-sample-create-vm-wordpress.md(0,0): Failed calling GitHub API '': The operation was canceled.
github-api-failed articles/virtual-machines/scripts/virtual-machines-linux-powershell-sample-create-vm-nginx.md(0,0): Failed calling GitHub API '': The operation was canceled.
github-api-failed articles/virtual-machines/scripts/virtual-machines-linux-powershell-sample-create-docker-host.md(0,0): Failed calling GitHub API '': The operation was canceled.
github-api-failed articles/virtual-machines/linux/tutorial-secure-web-server.md(0,0): Failed calling GitHub API '': The operation was canceled.
github-api-failed articles/virtual-machines/linux/tutorial-load-balancer.md(0,0): Failed calling GitHub API '': The operation was canceled.
github-api-failed articles/virtual-machines/linux/tutorial-jenkins-github-docker-cicd.md(0,0): Failed calling GitHub API '': The operation was canceled.
github-api-failed articles/virtual-machines/linux/tutorial-mean-stack.md(0,0): Failed calling GitHub API '': The operation was canceled.
github-api-failed articles/virtual-machines/linux/time-sync.md(0,0): Failed calling GitHub API '': The operation was canceled.
github-api-failed articles/virtual-machines/linux/tutorial-create-vmss.md(0,0): Failed calling GitHub API '': The operation was canceled.
github-api-failed articles/virtual-machines/linux/tutorial-availability-sets.md(0,0): Failed calling GitHub API '': The operation was canceled.
```

**Comment by herohua** [comment] 2019-01-26 12:14
I am closing this issue until it can be reproducible again.

**Closed by herohua** 2019-01-26 12:14 UTC
Labels: v3
