### ISSUE TITLE
DocFX VS Code preview doesn't show preview

### ISSUE THREAD

**Issue by JimDaly** [dotnet/docfx#2076] opened 2017-09-22 23:23 UTC
**DocFX Version Used**: 0.1.0

**Template used**: none

**Steps to Reproduce**:

1. Edit a markdown topic
2. Launch the preview (ctrl+shift+q)

**Expected Behavior**:
See a preview of my MD file in a new window

**Actual Behavior**:
New window with 'DfmPreview: < filename>.md opens
No preview displays

I've used earlier versions (DfmPreview, DocFXPreview) and they usually worked fine. They would display a little alert the first time to say 'wait while initializing'. This DocFx extension doesn't do that. Just nothing happens.

My content does use includes. I'm expecting this to slow things down, but not stop from displaying.

**Comment by 928PJY** [comment] 2017-09-25 05:36
hi, @JimDaly, it works for me
![docfxpreview](https://user-images.githubusercontent.com/17958546/30793626-e09533a8-a1f5-11e7-9037-3bc97386c49c.gif)

can you uninstall the obsolete extension(DocFXPreview, DFMPreview), reinstall this extension and try it again, if the problem still exists, please provide a sample which can repro this issue. Thank you!

**Comment by 928PJY** [comment] 2017-10-13 03:02
This issue is caused by Microsoft Internal VSCode extension.

**Comment by bobi-no** [comment] 2018-03-12 04:07
@928PJY I see this was closed and labeled **wontfix** . But I do not understand. I am having the same issue with the VSC DocFX 0.1.1 extension, except it refuses to display plain text (from a file saved with the .md file extension where the text has no syntax markers around it). The DocFX extension shows as published by Microsoft with no dependencies. It does the same if I take .md files coming from Microsoft .net documentation, so my file is not the problem. It is throwing back an error saying:

> [Child process Error]: 'C:\Users\myUser' is not recognized as an internal or external command, operable program or batch file.

How can I be doing anything wrong, this is a fresh install of VSC with no other extensions?

**Comment by sahammer** [comment] 2018-04-10 15:53
I have also experienced this error, it is specifically with the [DocFX](https://github.com/dotnet/docfx/tree/dev/tools/VscExtension) extension that in installed with the new Docs Markdown extension:

https://docs.microsoft.com/en-us/teamblog/docs-extension

I believe this is caused by a user profile that has a space in it. This issue should be re-opened.

**Comment by 928PJY** [comment] 2019-03-17 11:56
Hi all, thanks for using this extension, but please move to the [docs-markdown](https://marketplace.visualstudio.com/items?itemName=docsmsft.docs-markdown), `Docfx` will not be supported anymore.

**Closed** 2019-05-14 09:07 UTC
Labels: Area-Preview, bug
