### ISSUE TITLE
[Bug]  The title is not displayed in the bookmark hierarchy in a PDF document

### ISSUE THREAD

**Issue by MrDmitrij** [dotnet/docfx#9764] opened 2024-03-06 16:18 UTC
**Describe the bug**
A title starting with the Cyrillic characters "Ш" or "Щ" is not displayed in the bookmark hierarchy of a PDF document.
![image](https://github.com/dotnet/docfx/assets/78934708/fafaea76-b1e7-4e41-97bd-69bb7c995746)

**To Reproduce**
1. Create a TOC file with a name starting with the Cyrillic characters "Ш" or "Щ".
![image](https://github.com/dotnet/docfx/assets/78934708/25afbead-99e4-46f8-adf3-df110ca8236d)

3. Follow the instructions to generate a PDF from the documentation.

4. Open the PDF file and view the bookmark hierarchy.

**Expected behavior**
The bookmark hierarchy in PDF should be displayed correctly using the Cyrillic characters "Ш" or "Щ".

**Context (please complete the following information):**
- OS: Windows
- Docfx version: [e.g. 2.75.3]

**Comment by filzrev** [comment] 2024-03-07 10:55
> A title starting with the Cyrillic characters "Ш" or "Щ" is not displayed in the bookmark hierarchy of a PDF document.

On my environment. it can't reproduce problems.
I've create toc files that contains "Ш" /"Щ" chars and save file with UTF-8 encoding.  

Is it able to provide minimum reproducible source files?

**Comment by MrDmitrij** [comment] 2024-03-07 11:30
Yes, the name of the TOC node must begin with the characters "Ш" or "Щ".

**Comment by filzrev** [comment] 2024-03-09 11:46
PDF bookmarks problems seem to be caused by PdfPig library.
I've created a separate issue at PdfPig repository.
https://github.com/UglyToad/PdfPig/issues/789

**Comment by filzrev** [comment] 2024-03-12 07:43
PdfPig bookmark problems are resolved by #9783.

This issue will be resolved in next docfx release.

**Comment by MrDmitrij** [comment] 2024-04-29 07:17
> It's expected to be fixed with latest docfx version (v2.76.0).
> 
> @MrDmitrij Is it able to confirms problems are fixed in latest version?

@filzrev
Yes, the problems are fixed in the docfx version (v2.76.0). Everything works well. 

Thank you for your excellent work! =)

**Comment by filzrev** [comment] 2024-04-29 10:43
@MrDmitrij
Thanks for your confirmation.
Please close issue if no additional problems.

**Closed** 2024-04-30 07:05 UTC
Labels: bug, pdf
