### ISSUE TITLE
Bookmark anchors not included in xrefmap href property with statictoc template

### ISSUE THREAD

**Issue by tobiasbunyan** [dotnet/docfx#1256] opened 2017-01-30 12:55 UTC
### Functional impact
Generated links only reference the page, not the bookmark.

### Minimal repro steps
1. Create a class with two methods, document the methods.
2. Create a conceptual document and reference the methods (i.e. with `@` or `<xref:>`
2. Generate documentation with statictoc template

### Expected result
Method links in document include the bookmark to the method.

### Actual result
Method links are missing the bookmark element.

### Further technical details
This is confirmed if you look at the generated xrefmap.yml.  All the href properties are missing the bookmark anchor points.  Adding the following code from the default template ManagedReference.html.primary.js file to the bottom of the same file in the statictoc template seems to work.  I don't know however if this is the correct solution to the problem.

```
exports.getOptions = function (model) {
  return { "bookmarks": mrefCommon.getBookmarks(model) };
}
```

**Comment by superyyrrzz** [comment] 2017-02-03 02:20
@tobiasbunyan Thank you for your report. You found exactly the root cause. The statictoc template is out of sync with the default template. This will be fixed in Docfx 2.12

**Closed** 2017-03-29 07:03 UTC
