### ISSUE TITLE
Error extracting metadata for project XXX: System.ArgumentException: An item with the same key has already been added.

### ISSUE THREAD

**Issue by jplayer1978** [dotnet/docfx#4249] opened 2019-03-26 14:20 UTC
**Operation System**: (`Windows` or `Linux` or `MacOS`)
Windows 10 Pro

**DocFX Version Used**: 
2.40.12

**Template used**: (`default` or `statictoc` or contain custom template)
Default

**Steps to Reproduce**:

1.  Include single project in docfx.json
2. Build docfx project
3. receive error --> Error extracting metadata for project XXX: System.ArgumentException: An item with the same key has already been added.

**Expected Behavior**:
Documentation to be built.

**Actual Behavior**:
Error extracting metadata for project XXX: System.ArgumentException: An item with the same key has already been added.
Documentation is not built.

**ADDITIONAL COMMENTS**
If I target a different project it will work however there are 3 or 4 projects within this solution that exhibit this same issue.  I have looked for duplicate references and many other items and cannot find anything glaring that should cause this issue.

Thanks for your assistance.

**Comment by superyyrrzz** [comment] 2019-03-26 15:15
Could you provide a sample repo to help reproduce the issue? Related: #1414 #2532 #3778 , while I think #1420 should already fix this.

**Comment by jplayer1978** [comment] 2019-03-26 18:18
I am unable to share the project, I could share a csproj file if that would be helpful..  I have also checked for duplicate refs and pretty much anything else that I could find about the issue online.  Are there any other recommendations?

**Comment by superyyrrzz** [comment] 2019-03-27 04:02
A log containing error call stack may be helpful.

**Comment by superyyrrzz** [comment] 2019-04-12 09:35
dupe of #2532

**Closed by superyyrrzz** 2019-04-12 09:35 UTC
