### ISSUE TITLE
Too many properties/methods at sidebar

### ISSUE THREAD

**Issue by jeffffc** [dotnet/docfx#3038] opened 2018-07-10 09:40 UTC
**DocFX Version Used**: 2.36.2

**Template used**: `default`

**Steps to Reproduce**:

1. Normal docfx procedures

**Expected Behavior**:
The sidebar should be scrollable to show all methods/properties etc.

**Actual Behavior**:
The sidebar at the side affix cannot show all methods/properties if there are too many. 
Example: [Here (Methods)](https://crazypokemondev.github.io/TelegramBotApi/api/TelegramBotApi.TelegramBot.html#methods)
![image](https://user-images.githubusercontent.com/15724935/42502174-ed94abec-8467-11e8-9896-42ba3c42ca55.png)
When you keep scrolling down until you get past the last item shown in the navbar, the "current item" bolding disappears and does not go downwards anyways. Next sub-section disappear too (e.g. [Here (Events)](https://crazypokemondev.github.io/TelegramBotApi/api/TelegramBotApi.TelegramBot.html#events) is after methods)

**Comment by cstamatopoulos** [comment] 2018-07-12 23:18
Having the same issue .
Regression ?
https://github.com/dotnet/docfx/issues/214

**Comment by stocktrader8888** [comment] 2019-03-16 02:23
Same issue.  Edge and Chrome.  DocFx 2.40.12. 

I have a LOT of methods (like 70 of them) but the "In this Article" methods doesn't scroll past the first 20 or so.

**Comment by jifka** [comment] 2019-04-01 15:29
Bump?

**Comment by MrGadget1024** [comment] 2019-08-31 18:49
**BUMP**

**Comment by alphaleonis** [comment] 2019-11-14 14:56
Bug is still here in 2.47.0 :(

**Comment by silvesterpang** [comment] 2020-04-27 02:38
bug is still here in 2.52.0 :(

**Comment by jifka** [comment] 2020-04-27 04:51
I’ve had to do some CSS work to get around this but I’ve made it fully scrollable. But one library I had to document had hundreds of methods because of multiple overloads, and the whole thing takes about 10-15 seconds to render. For that I had to put a loading screen in place.

**Comment by varunmankal** [comment] 2020-07-02 18:36
@jifka can you share some details on how were you able to fix this ? 
any css properties ? For which elements did you apply css properties to enable scrolling ?

**Comment by proprunner** [comment] 2020-07-05 21:13
> @jifka can you share some details on how were you able to fix this ?
> any css properties ? For which elements did you apply css properties to enable scrolling ?
> Or Any other workarounds ?

First I added the following to the .sideaffix CSS class:
    margin-top: 50px;
    font-size: 12px;
    max-height: 100%;
    overflow: hidden;
    top: 100px;
    bottom: 10px;
    position: fixed;

Spacing is up to you based on any other layout you may have applied. But the key is forcing the overflow:hidden so the contents scroll.

Next, I added a coverall element that's a grey'd out screen with "API Loading..." text in the center that gets removed on a jQuery $(document).ready() call. This ensures that when the page gets all of the elements rendered, the coverall goes away. Without it, the screen just sits there calculating all of the API methods and properties without any user feedback.

**Comment by jifka** [comment] 2020-07-05 21:14
First I added the following to the .sideaffix CSS class:
margin-top: 50px;
font-size: 12px;
max-height: 100%;
overflow: hidden;
top: 100px;
bottom: 10px;
position: fixed;

Spacing is up to you based on any other layout you may have applied. But the key is forcing the overflow:hidden so the contents scroll.

Next, I added a coverall element that's a grey'd out screen with "API Loading..." text in the center that gets removed on a jQuery $(document).ready() call. This ensures that when the page gets all of the elements rendered, the coverall goes away. Without it, the screen just sits there calculating all of the API methods and properties without any user feedback.

**Comment by d-vs** [comment] 2020-07-26 11:23
The fix posted by @jifka didn't work for me. I have a temporary workaround until this is fixed. A combination of some javascript and css.

/* Hide scrollbar for Chrome, Safari and Opera */
.affix > ul.level1::-webkit-scrollbar {
    display: none;
}

/* Hide scrollbar for IE, Edge and Firefox */
.affix > ul.level1 {
    -ms-overflow-style: none; /* IE and Edge */
    scrollbar-width: none; /* Firefox */
}

$(window).on("load", function () {
    let _scrollTimeout = null;

    function onScrollTimeout() {
        let $level1ActiveItem = $(".sideaffix ul.level1 li.active");

        if (!$level1ActiveItem.length) {
            $(".sideaffix ul.level1").css("overflow-y", "hidden");
            console.info("overflow reset");
            return;
        }

        let $level1 = $level1ActiveItem.closest("ul"),
            $level2 = $("ul.level2", $level1);

        if ($level1.outerHeight() < $level2.outerHeight()) {
            $level1.css("overflow-y", "scroll");
            console.info("overflow shown");
        } else {
            $level1.css("overflow-y", "hidden");
            console.info("overflow hidden");
        }
    }

    $(window).on("scroll", function () {
        if (_scrollTimeout) {
            clearTimeout(_scrollTimeout);
        }
        _scrollTimeout = window.setTimeout(onScrollTimeout, 500);
    });
});

**Comment by d-vs** [comment] 2020-07-26 11:46
The fix posted by @jifka didn't work for me. I have a workaround involving some javascript and css.

```css
/* Hide scrollbar for Chrome, Safari and Opera */
.affix > ul.level1::-webkit-scrollbar {
    display: none;
}

/* Hide scrollbar for IE, Edge and Firefox */
.affix > ul.level1 {
    -ms-overflow-style: none; /* IE and Edge */
    scrollbar-width: none; /* Firefox */
}
```

```javascript
$(window).on("load", function () {
    let _scrollTimeout = null;

    function onScrollTimeout() {
        let $level1ActiveItem = $(".sideaffix ul.level1 li.active"),
            $level1 = $level1ActiveItem.closest("ul");

        if (!$level1ActiveItem.length) {
            $level1.css("overflow-y", "hidden");
            return;
        }

        let $level2 = $("ul.level2", $level1);

        if ($level1.outerHeight() < $level2.outerHeight()) {
            $level1.css("overflow-y", "scroll");
        } else {
            $level1.css("overflow-y", "hidden");
        }
    }

    $(window).on("scroll", function () {
        if (_scrollTimeout) {
            clearTimeout(_scrollTimeout);
        }
        _scrollTimeout = setTimeout(onScrollTimeout, 500);
    });
});
```

**Comment by bakx** [comment] 2020-09-08 21:21
This is still an issue with the latest version to date and the static template. No one has a proper fix?

**Comment by glopesdev** [comment] 2021-12-29 01:19
Still an issue more than one year later. This seems especially important since there doesn't seem to be a good default way to have a TOC for methods in a class. For static classes with lots of methods this is a huge problem.

**Comment by glopesdev** [comment] 2021-12-29 01:35
@bakx This seems to be a duplicate of #5671 and there is a nice working solution by @WonyoungChoi at the end.

**Closed** 2023-03-14 04:22 UTC
Labels: template
