### ISSUE TITLE
Support REST API

### ISSUE THREAD

**Issue by chenkennt** [dotnet/docfx#181] opened 2016-02-29 09:23 UTC

**Comment by vicancy** [comment] 2016-05-11 02:04
It's now supported. `docfx-seed` adds 2 swagger file into the project https://github.com/docascode/docfx-seed/tree/master/restapi and the result looks like: http://docascode.github.io/docfx-seed/restapi/petstore.html

**Comment by vdecristofaro** [comment] 2016-05-13 22:37
Hello @vicancy ,
I have created a swagger file by using NSwag tool. I have placed the json file inside a "restapi" folder and then added a toc.md as you have made in your example.

I am getting an exception when building the docs which says 

```
Error: System.AggregateException: One or more errors occurred. ---> 
Newtonsoft.Json.JsonException: type is already defined in referenced object "#/definitions/XXXXXX".
   at Microsoft.DocAsCode.Build.RestApi.Swagger.Internals.SwaggerObjectConverter.WriteJson(JsonWriter writer, Object value, JsonSerializer serializer) in C:\Users\qinzhu\workspace\docfx-latest\src\Microsoft.DocAsCode.Build.RestApi\Swagger\Internals\SwaggerObjectConverter.cs:line 40

Any suggestion?
```

**Comment by vicancy** [comment] 2016-05-14 23:56
Is the swagger file contains such code block:
```json
{
    "$ref": "#/definitions/XXXX",
    "type": "XX"
}
```
and inside `#/definitions/XXXX` it also contains key `type`?
Such case it throws exception.

**Comment by vdecristofaro** [comment] 2016-05-15 11:33
@vicancy Right.

this is an extract of the generated swagger

```
    "cp/redeem": {
      "Put": {
        "tags": [],
        "operationId": "Coupon_RedeemCoupon",
        "parameters": [
          {
            "name": "model",
            "in": "body",
            "required": false,
            "schema": {
              "type": [
                "null",
                "object"
              ],
              "$ref": "#/definitions/CouponRedeemViewModel"
            }
          }
        ],
        "responses": {
          "200": {
            "schema": {
              "type": "file"
            }
          }
        }
      }
    },

```

How would you then advice to solve this problem. Is this an issue with docfx?

**Comment by vicancy** [comment] 2016-05-15 12:51
why there is extra
```

              "type": [
                "null",
                "object"
              ],
```
inside `schema`? it is not valid. I would suggest remove that block.

**Comment by vdecristofaro** [comment] 2016-05-18 23:37
Hello @vicancy as you can see in my referenced issue that has been solved and now generate exactly the code reported by the NSwag project owner. I have also updated the docfx to 1.9.3.
 However I am still getting the same error .
Could you please tell me how did you generate your json sample? 

Thank you!

**Comment by hellosnow** [comment] 2016-05-27 05:10
@vdecristofaro could you provide the json file or github repo for us? I will investigate for you. Thanks.

**Comment by vdecristofaro** [comment] 2016-05-27 12:06
Sure @hellosnow. Here is a simple file I am using as a sample. the file is generated by using NSwag tool which by using the WebApiToSwagger generator described [here](https://github.com/NSwag/NSwag/wiki/CommandLine).

Thanks!

[tmp_swagger.txt](https://github.com/dotnet/docfx/files/286412/tmp_swagger.txt)

**Comment by hellosnow** [comment] 2016-05-30 07:31
@vdecristofaro , I checked your attached swagger json and found its schema is invalid. Could you work with NSwag tool to generate the valid swagger json file? I use http://bigstickcarpet.com/swagger-parser/www/index.html to validate the swagger file, for example "typeName", "enumNames" and "oneOf" is not valid.

Some valid swagger files example: http://petstore.swagger.io/v2/swagger.json
Swagger schema: http://swagger.io/specification/

**Comment by hellosnow** [comment] 2016-05-30 07:33
We also have plan to validate the swagger schema #312

**Comment by vdecristofaro** [comment] 2016-05-30 22:33
@hellosnow 
First of all thank you for your answer.
This is getting very strange and I can't understand the way to solve this. 
I have tried to pass a Swashbuckle generated json to the bigstickcarpet  parser and it tells me that is invalid. Also NSwag generated file is invalid. 

Could you please advice which kind of swagger generator should I use to create my swagger file?

**Comment by hellosnow** [comment] 2016-06-01 09:39
Hi @vdecristofaro ,

- For "circular references", as the validation tool hints, that's an invalid case and docfx doesn't support it. For example, if A's type is defined as B while B's type is defined as A, docfx could not resolve the real type.
- For NSwag generated invalid json, I suggest you to file some issue and see whether they can help you to address the root cause to lead to invalid swagger file? Is it code bug of NSwag or incorrect type reference definition in your client/server side?

Considering not sure which language you're using to write for the client/server side, here's the swagger official tools: http://swagger.io/tools/, could you check if there's any suitable for you?

**Comment by domecbuilder** [comment] 2016-06-01 22:58
Hi @hellosnow,
My project is an ASP.NET web api 2.2 project (.Net 4.6.1).
Let me give you a bit of reference on what I am doing

- I have integrated the [Swashbuckle](https://github.com/domaindrivendev/Swashbuckle) nuget package in the web api and I am really enjoying the swagger documentation generated. To create a much more detailed documentation for my API I am evaluating DocFX. Because DocFX require a single json for every API I have also filled an [issue](https://github.com/domaindrivendev/Swashbuckle/issues/764) to Swashbuckle to ask if it is possible to generate a single json for every controller.
- Regarding NSwag. I have done exactly what you suggest here. The project owner told me that the problem seems to be related to the fact that Newtonsoft does not handle JSON Schema v4 as specified by the Swagger specification. You can follow the entire discussion [here](https://github.com/NSwag/NSwag/issues/108). As the NSwag project owner says in the issue I dont really understand why a path in the file get validated with the message `Additional properties not allowed: cp/redeem,cp/create at #/paths`. 

Apart from this, I still do not understand where the circular reference would be. The Swashbuckle generated JSON is correctly handled by the swagger-ui package which shows the generated documentation. I really dont know how to proceed here.

**Comment by vdecristofaro** [comment] 2016-06-01 22:59
Hi @hellosnow,
My project is an ASP.NET web api 2.2 project (.Net 4.6.1).
Let me give you a bit of reference on what I am doing

- I have integrated the [Swashbuckle](https://github.com/domaindrivendev/Swashbuckle) nuget package in the web api and I am really enjoying the swagger documentation generated. To create a much more detailed documentation for my API I am evaluating DocFX. Because DocFX require a single json for every API I have also filled an [issue](https://github.com/domaindrivendev/Swashbuckle/issues/764) to Swashbuckle to ask if it is possible to generate a single json for every controller.
- Regarding NSwag. I have done exactly what you suggest here. The project owner told me that the problem seems to be related to the fact that Newtonsoft does not handle JSON Schema v4 as specified by the Swagger specification. You can follow the entire discussion [here](https://github.com/NSwag/NSwag/issues/108). As the NSwag project owner says in the issue I dont really understand why a path in the file get validated with the message `Additional properties not allowed: cp/redeem,cp/create at #/paths`. 

Apart from this, I still do not understand where the circular reference would be. The Swashbuckle generated JSON is correctly handled by the swagger-ui package which shows the generated documentation. I really dont know how to proceed here.

**Comment by hellosnow** [comment] 2016-06-02 10:08
@vdecristofaro I will look into the Swashbuckle and NSwag tomorrow carefully and give you update later. But I just did one testing on official swagger io and found it cannot be processed:

1. Open http://petstore.swagger.io/
2. Enter your swagger url: https://raw.githubusercontent.com/hellosnow/docfx-seed/issue181/restapi/tmp_swagger.json, which I just uploaded in my repo.
3. Click `Explore`.
4. Check error report at http://online.swagger.io/validator/debug?url=https://raw.githubusercontent.com/hellosnow/docfx-seed/issue181/restapi/tmp_swagger.json
5. the validation error is same with the one in http://bigstickcarpet.com/swagger-parser/www/index.html?

- Additional properties not allowed: cp/redeem,cp/create at #/paths.

- TypeName and EnumName

**Comment by rsuter** [comment] 2016-06-02 22:27
In NSwag v2.43, the missing `/` prefix is added to the paths and the `typeName` and `enumNames` fields are prefixed with `x-` (custom fields). Now the generated Swagger spec should be valid...

**Comment by hellosnow** [comment] 2016-06-03 03:00
Thanks @rsuter for the quick update. @vdecristofaro could you try to generate the new Swagger json file by NSwag v2.43? We can try to parse the new generated json file in docfx and see whether it works.

**Comment by vdecristofaro** [comment] 2016-06-03 08:43
I did it. DocFX now still end with error during the build 

```
Info: Completed building documents in 2208,5322 milliseconds.
Info: Completed executing in 3194,5989 milliseconds.
Error: System.AggregateException: One or more errors occurred. ---> Newtonsoft.Json.JsonException: type is already defined in referenced object "#/definitions/ReceiptProduct". at Microsoft.DocAsCode.Build.RestApi.Swagger.Internals.SwaggerObjectConverter.WriteJson(JsonWriter writer, Object value, JsonSerializer serializer)
```

I have tried to parse the resulting json at [http://bigstickcarpet.com/swagger-parser/www/index.html](http://bigstickcarpet.com/swagger-parser/www/index.html) and i get the following error

```
Swagger schema validation failed. 
  Additional properties not allowed: oneOf at #/definitions/Payment/properties/Method
 
JSON_OBJECT_VALIDATION_FAILED
```.

I am attaching the new json file here. Thanks for helping


[tmp_swagger.txt](https://github.com/dotnet/docfx/files/297243/tmp_swagger.txt)

**Comment by rsuter** [comment] 2016-06-03 08:56
Ok, now the problem is probably that JSON.net just supports JSON Schema v3, but Swagger requires v4. 
See link at bottom: https://github.com/json-schema/json-schema/wiki/anyOf,-allOf,-oneOf,-not
As I told, I implemented the whole Swagger object model + JSON Schema v4 in http://nswag.org (nuget: NSwag.Core)

**Comment by hellosnow** [comment] 2016-06-03 14:15
Seems `oneOf` is not supported by swagger? Discussions are on [Support oneOf](https://github.com/swagger-api/swagger-ui/issues/1056): "Swagger use an extended subset of JSON Schema, and explicitly don't support oneOf", refer to  [Swagger schema definition](http://swagger.io/specification/#schemaObject)

**Comment by rsuter** [comment] 2016-06-03 15:04
Oh well, what a mess this Swagger is...

**Comment by rsuter** [comment] 2016-06-03 15:07
Without oneOf you cannot express a nullable property which references another schema (which is not nullable)..

**Comment by vdecristofaro** [comment] 2016-06-04 13:17
Well, at the least we clarified something. 
Despithe the fact that, as it seems to me NSwag cannot be taken in account to generate swagger files, could you please provide an alternative which works with DocFX?

I have a project with more than one hundred api endpoints. How can I use DocFX to generate documentation? Do you suppose that swaggers have to be created manually?

**Comment by rsuter** [comment] 2016-06-04 15:19
I'd like to support this/more scenarios but I need to know how to work around these issues: 
see https://github.com/swagger-api/swagger-ui/issues/1056#issuecomment-223669807

**Comment by hellosnow** [comment] 2016-06-06 09:23
As far as I know, Swashbuckle is ok. @vdecristofaro I remember you used this tool to generate json filw right? Could you provide it to us to test whether it's valid Swagger file?

**Comment by vdecristofaro** [comment] 2016-06-09 23:07
@hellosnow 
Well I had the time to do some testing and got some results to share.

- I can confirm that Swashbuckle is ok. However there is a problem in using it and it is due to the fact that Swashbuckle only generates a single json file with all the endpoints and api exposed from my project. This behaviour has the side effect that docfx generate a single page documenting all the endpoints. In my scenario these endpoints are more than 100 and this produce a slow loading page with over 100 links on the right side menu. Moreover does not give me the chance to fully organize those endpoints in logical related categories by using features of the toc.md (left side menu). As you can see [here](https://github.com/domaindrivendev/Swashbuckle/issues/764) I have already asked for help on generating a single json file for every API controller.

- With the help of @rsuter I am now able to generate a single file for every controller by using NSwag. The generated swaggers are fully validated [here](http://bigstickcarpet.com/swagger-parser/www/index.html) (please try yourself by using the attached swagger sample at the end of this message). However when using the NSwag generated files DocFX now raise the following error:

```
Error: System.AggregateException: One or more errors occurred. ---> Newtonsoft.Json.JsonSerializationException: Self referencing loop detected with type 'Microsoft.DocAsCode.Build.RestApi.Swagger.Internals.SwaggerObject'. Path ''.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.CheckForCircularReference(JsonWriter writer, Object value, JsonProperty property, JsonContract contract, JsonContainerContract containerContract, JsonProperty containerProperty)
```

Could you please check why this error occur now?

Thank you.

**Comment by hellosnow** [comment] 2016-06-13 15:07
@vdecristofaro I tried to parse the attached json by docfx and it succeeded without error? Which docfx version are you using? Suggest to update to latest bits [2.0.1](https://github.com/dotnet/docfx/releases/tag/v2.0.1)

I will continue to look into your json on the final formatting. Also I filed some known issue #358 #360 , and will look at #223 , thanks for pointing out.

**Comment by hellosnow** [comment] 2016-07-06 06:42
Hello @vdecristofaro , how's everything going for rest swagger?

For loop reference issue, we have fixed via #453 and #464 .The code is already in dev branch, will release at July 18th.

Also, we support more syntax via #358, #359 and #360 . 

Could you have a try for your project? Any further issues please let us know.

**Comment by vdecristofaro** [comment] 2016-07-07 00:45
Great. I will tra to run afgani my test on this and feedback quickly.
Thanks for support

**Comment by vdecristofaro** [comment] 2016-08-16 13:37
@hellosnow I had the chance to run all my test against the latest release and can confirm that the issue has been solved. the issue can be closed.
Thanks a lot for the collaboration and help!

**Comment by hellosnow** [comment] 2016-08-17 02:28
@vdecristofaro glad to hear that, will close the issue now.

**Closed by hellosnow** 2016-08-17 02:28 UTC
