### ISSUE TITLE
[Bug] Invalid cref value "!:ObservableObject" in WPF UserControl

### ISSUE THREAD

**Issue by RobGess** [dotnet/docfx#10259] opened 2024-10-11 09:31 UTC
When using the ObservableObject attribute from the CommunityToolkit.Mvvm v8.3.2 package on the code behind partial class of a WPF UserControl like this:

![Image](https://github.com/user-attachments/assets/f1ff4525-d9d9-4528-94b2-1f799b5c03f7)

DocFx seems to have an issue with properly generating the code documentation for the SourceGenerators. The following warning occurs when generating the documention with DocFx v.2.77.0:

`warning: InvalidCref: Invalid cref value "!:ObservableObject" found in XML documentation comment for SetProperty defined in CommunityToolkit.Mvvm.SourceGenerators\CommunityToolkit.Mvvm.SourceGenerators.ObservableObjectGenerator\DocFxTest.TestControl.g.cs Line 243.`

I am aware that the proper way to handle this kind of functionality should utilize a view model. Also, ObservableObject used in view models don't have this issue with DocFx.

Feel free to have a look at my test project [DocFxTest](https://github.com/RobGess/DocFxTest) to reproduce this issue.

If this is an user issue and can be solve with a proper docfx.json configuration, please let me know.

Spec Summary:
- Windows 11
- CommunityToolkit.Mvvm 8.3.2
- DocFx 2.77.0

**Expected behavior**
No warning.

**Comment by filzrev** [comment] 2024-10-11 12:10
Reported issue seems to be caused by `CommunityToolkit.Mvvm` source generator side problems.

When Roslyn failed to  resolve symbol.
It's resolved with `!:` prefixed name. And docfx reporting this name as `InvalidCref` warnings.
https://github.com/dotnet/roslyn/blob/d5a5b2101b5ddc32adca0d7b517899607c404332/src/Compilers/CSharp/Portable/DocumentationComments/DocumentationCommentIDVisitor.cs#L86-L92

**Steps to confirm root cause of problem**

1. Open `DocfxTest` project with Visual Studio.
2. Open generated `DocFxTest.TestControl.g.cs`  file from Solution Explorer.  
    > TreePath: 
    > [Dependencies]-[Analyzers]-[CommunityToolkit.Mvvm.SourceGenerators]-[CommunityToolkit.Mvvm.SourceGenerators.ObservableObjectGenerator]
3. Confirm  `<see cref = "ObservableObject"/>` symbol reference is not resolved (It's not highlighted)

**How to fix problems**
I should be referenced by using fully qualified name.
(e,g, `<see cref = "global::CommunityToolkit.Mvvm.ComponentModel.ObservableObject"/>`)

**Comment by RobGess** [comment] 2024-10-21 12:06
I can confirm that the symbol reference is not resolved (see image).

![Image](https://github.com/user-attachments/assets/3c6ad1ad-67c6-4cca-9293-f6f9de0aa56a)

Unfortunately, I was not able to edit the *.g.cs file generated by the ObservableObjectGenerator to try the suggested fix.

**Comment by filzrev** [comment] 2024-10-21 12:28
It need to be fixed by [CommunityToolkit.Mvvm](https://github.com/CommunityToolkit/dotnet) project side.

I thought it can be fixed by changing following line.
https://github.com/CommunityToolkit/dotnet/blob/v8.3.2/src/CommunityToolkit.Mvvm/ComponentModel/ObservableObject.cs#L275

**Comment by RobGess** [comment] 2024-10-21 12:45
Alright, thank you. I will open the issue in the CommunityToolkit.Mvvm project.

**Closed** 2024-10-23 02:51 UTC
Labels: bug
