### ISSUE TITLE
[Bug] Additional tabs not shown in PDF output

### ISSUE THREAD

**Issue by cjlotz** [dotnet/docfx#9565] opened 2023-12-28 11:29 UTC
**Describe the bug**
Additional tabs are not shown as part of PDF output

**To Reproduce**
1. Create simple tab based output using the [docfx sample steps](https://dotnet.github.io/docfx/docs/markdown.html?q=tab&tabs=linux%2Cdotnet#tabs)
2. Enable PDF output for the site
3. Build the content

**Expected behavior**
The content for all output should be displayed in the PDF output beneath each other.  Currently only the content of the default tab is shown in the PDF.

**Context (please complete the following information):**
- OS: Windows
- Docfx version: 2.74.1

**Comment by filzrev** [comment] 2023-12-28 16:17
It seems duplicate of #3663.

As described on above issue.
There is workaround that applying custom CSS when rendering  `pdf` HTML.

## Steps

1. Create custom template folder (e.g. `templates/custom`)
2. Specify `templates/custom` to `template` section of `docfx.json`
3. Place `templates/custom/public/main.css` file with following contents
```css
@media print {
  section[role="tabpanel"] {
    display: block !important;
  }
}
```
## Result Image
![image](https://github.com/dotnet/docfx/assets/103790468/b0a63d7f-0e6c-4d6f-8355-4b2103241045)

If it's required more pretty looking HTML.
It needs to customize CSS or custom HTML DOM rewriting.

**Closed** 2023-12-28 17:27 UTC
Labels: bug
