### ISSUE TITLE
Path to pdf engine

### ISSUE THREAD

**Issue by bahusoid** [dotnet/docfx#4422] opened 2019-04-25 04:59 UTC
**Operation System**: `Windows` 
**DocFX Version Used**: 2.44

[wkhtmltopdf](https://www.nuget.org/packages/wkhtmltopdf.x64/) is available as nuget package. So it would be good to support it without  adding it to PATH.
For instance by providing relative path to exe in `docfx.json`:
```json
"pdf": {
    "pdf_engine": "../packages/wkhtmltopdf/wkhtmltopdf.exe",
  }
```

**Comment by icnocop** [comment] 2020-05-15 10:55
Duplicate of https://github.com/dotnet/docfx/issues/4422

**Closed** 2020-05-18 15:52 UTC
Labels: Area-Pdf, feature-request

**Comment by icnocop** [comment] 2020-05-29 19:32
docfx 2.54 now supports the ability to set the path to wkhtmltopdf.

See https://dotnet.github.io/docfx/tutorial/docfx.exe_user_manual.html#331-properties-for-the-wkhtmltopdf-key

**Comment by DaviddH** [comment] 2020-06-05 08:09
Would it be possible to also add the property to specify the path to the  wkhtmltopdf executable in the command line arguments?

**Comment by icnocop** [comment] 2020-06-05 19:23
@DaviddH , yes, this is already implemented.
The documentation indicates:

`filePath | The path and file name of a wkhtmltopdf.exe compatible executable.`

**Comment by DaviddH** [comment] 2020-06-06 15:58
Yes, but that is configured in the docfx.json, I'm looking for an option to configure it using the command line. 
As far as I can see in the code that is not implemented.
https://github.com/dotnet/docfx/blob/b5d5be90944ff4431c489fc364358b303ea68845/src/docfx/Models/PdfCommandOptions.cs
