### ISSUE TITLE
Allow redirecting the obj/xdoc cache directories created during docfx metadata command

### ISSUE THREAD

**Issue by rschili** [dotnet/docfx#1156] opened 2017-01-11 19:59 UTC
### Title
During docfx metadata, for each project.json file docfx will put an obj/xdoc/ directory alongside. This process is mentioned here: https://github.com/dotnet/docfx/blob/master/Documentation/spec/docfx_incremental.md
I need to keep the src directory clean, and this is the only thing that cannot be redirected.

### Functional impact
I'm trying to introduce docfx in our company. We have a build process which is very strict about tools polluting the source directory.
Since I cannot redirect these cache directories I need to delete them in a script, or copy the src directory before calling docfx metadata.

### Minimal repro steps
1. Create new .net core project using dotnet new
2. Set up docfx init, allow api documentation from the .net core project directory like this:
  "metadata": [
    {
      "src": [
        {
          "files": [
            "src/**project.json"
          ],
          "exclude": [
            "**/obj/**",
            "**/bin/**",
            "output/**"
          ]
        }
      ]

3. call docfx metadata, it will produce that obj/xdoc directory cache

**Comment by tommikiviniemi-srs** [comment] 2019-05-15 21:32
This issue right here may be preventing me from starting to use DocFx.

**Comment by Zastai** [comment] 2020-04-10 18:01
Why is it created in the src tree at all - for a project like docfx, it seems to me like any source dir (especially outside of the docfx project tree) should be considered read-only. As a user, if I specify a source location, I certainly don't expect changes to be made to it - it's a source, not a target.

Why not create some sort of manifest file in the docfx project directory that links source paths to guids, and then store what's in `{src}/obj/xdoc` now in a something like `obj/xdoc/{mapped-src-guid}` instead?

**Comment by Zastai** [comment] 2020-04-10 18:06
And for me too, this is currently one of the dealbreakers for using docfx, alongside the lack for inheritdoc (when the base doc is from a different package, which is, frankly, quite common) and the fact that the merge processing (for consolidating docs for multiple target frameworks) throws a NullReferenceException.

**Comment by AndrewRH** [comment] 2021-05-14 13:01
Upvote - docfx is polluting my source folder with this obj/xdoc folder which means I need to add another step to my build/packaging process to remove it.

**Comment by AndrewRH** [comment] 2021-05-14 13:12
FYI I made a workaround for this issue by making the first item in 'files' a dummy .cs script that lives outside of my source structure.  I had to give this a filename starting with 'aaaa' to make sure that it was parsed first alphabetically - this makes the /obj/xdoc folder appear on the same level as this file and not in my source folder.

**Comment by ChristianTellefsen** [comment] 2021-05-25 12:31
> FYI I made a workaround for this issue by making the first item in 'files' a dummy .cs script that lives outside of my source structure. I had to give this a filename starting with 'aaaa' to make sure that it was parsed first alphabetically - this makes the /obj/xdoc folder appear on the same level as this file and not in my source folder.

Thanks for this idea, I am having issues with DocFx trying to create temp files for Unity UPM packages inside a read-only Unity Library folder...

**Comment by jnoelbl** [comment] 2021-05-26 22:01
Upvote, this has made me move back to other documentation generation tools for the time being. I much prefer the look and setup of DocFX, but these intermediate files really mess with unity. I wasn't able to make the workaround from AndrewRH work either.

**Comment by DmitriyYukhanov** [comment] 2022-03-30 19:30
Thanks for the workaround @AndrewRH.

I wonder why this incremental format spec doc is not showing up at the [specs website](https://dotnet.github.io/docfx/spec/metadata_format_spec.html) as it could help get the xdoc cache generation logic: https://github.com/dotnet/docfx/blob/7fae1ef2c69ae448bbecede12b8670e5408e1d71/Documentation/spec/docfx_incremental.md?plain=1#L14 is 

It worked fine for me, here is an example for the metadata's src:

```
{
  "files": [
    "Docfx-project/!dummy.cs",
    "Sources/**/*.cs"
  ],
  "src": "../../../"
}
```

This way, the obj/xdoc goes to the `Docfx-project/obj/xdoc` instead of `Sources/obj/xdoc`.

**Comment by Sov3rain** [comment] 2022-06-16 14:28
Any news on this? This is the one thing preventing me from using DocFx with Unity.

**Comment by yufeih** [comment] 2023-02-06 13:46
Fixed by https://github.com/dotnet/docfx/pull/8388

**Closed by yufeih** 2023-02-06 13:46 UTC
Labels: dotnet

**Comment by adamgit** [comment] 2023-10-06 16:03
> Thanks for the workaround @AndrewRH.
> 
> It has an important note on the xdoc cache generation logic:
> 
https://github.com/dotnet/docfx/blob/7fae1ef2c69ae448bbecede12b8670e5408e1d71/Documentation/spec/docfx_incremental.md?plain=1#L14
> 

After a bit of trial and error wondering why this workaround had no effect ... in the doc you linked the line above is critical, which essentially says "if there are csproj files in your project - you're screwed, docfx will spam your source folder and there's nothing you can do to stop it".

Any other known workarounds for this? docfx is too buggy to upgrade (we're reliant on MANY things that got broken in later versions, so we're version-locked and having experienced the pain of trying to upgrade it in the past - weeks of lost time finding all the regressions - upgrading seems a very bad idea).

**Comment by adamgit** [comment] 2023-10-06 16:24
Oh! More trial and error: Docfx counts the "." in "../" as part of the filename when sorting, even though that's ... just not.

So if you are (sensibly) storing your source code in a folder that is NOT a child of docfx, and you have something like this:

`{
"src":[
          "src": "../sourcecode/",
          "files": [
            "Runtime/**.cs"
          ]
        }
]
}`

... you need to insert an extra 'src' entry that is strictly a subfolder of your docfx folder, e.g.:

`
{
          "files": [
            "aaa-microsofts-obj-cache-must-be-alphabetically-first-name/aaaaaaFakeClassForMicrosoft.cs"
          ]
        },
`
... noting that you CANNOT do this with "src:{ src: ../whereIwantittogo, files:[fakefile.cs]} because of the leading "."

Giving something like this:

`
"src": [
        {
          "files": [
            "aaa-cache-must-be-alphabetically-first-name/aaaaaaFakeClassForMicrosoft.cs"
          ]
        },
        {
          "src": "../source/",
          "files": [
            "Runtime/**.cs"
          ]
        }
      ],
`
