### ISSUE TITLE
New feature request: multilingual documentation

### ISSUE THREAD

**Issue by FSharpCSharp** [dotnet/docfx#2025] opened 2017-09-04 06:17 UTC
Until now, the documentation is unfortunately only monolingual. There are not such correct mechanisms or recommendations on how to deal with multilingualism.

Mechanisms should therefore be provided to easily switch between languages or to have an automatic mechanism that makes it very easy to add other languages.

**Comment by iwhp** [comment] 2017-09-14 15:59
What would be the current (v2.24) suggestion?
Is having a separate project an overkill or the only way to go?
Is it possible to have a unique TOP NAVIGATION for another language in the same project?
Thankx, Harry

**Comment by icnocop** [comment] 2018-01-21 11:42
For reference, this may be a duplicate of https://github.com/dotnet/docfx/issues/803

**Comment by superyyrrzz** [comment] 2018-06-12 09:34
duplicate of #803

**Closed by superyyrrzz** 2018-06-12 09:34 UTC
Labels: 5 - in discussion, Area-Localization, Area-Usability
