### ISSUE TITLE
Unable to process files with url-escaped symbols in names

### ISSUE THREAD

**Issue by mrEDitor** [dotnet/docfx#5132] opened 2019-09-24 09:05 UTC
**Operation System**: (`Windows` or `Linux` or `MacOS`)
tested on Windows

**DocFX Version Used**: 
2.39.2.0 (reproducable at 2.45.1 as well)

**Template used**: (`default` or `statictoc` or contain custom template)
`default`

**Steps to Reproduce**:
1. name the file with %2D or any other url-escape code, e.g. `im%2Descaped.md` (as azure devops wiki does)
2. use `"files": [ "*.md" ]` in docfx.json
3. try to build

**Expected Behavior**:
document builds

**Actual Behavior**:
```
Build failed.
[19-09-24 08:42:50.944]Error:System.IO.DirectoryNotFoundException: Unable to find part of path "D:\md\azurewiki2docfx\sources\im%2Aescaped.md".
   в System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
```

[Minimal reproducible example (ZIP)](https://github.com/dotnet/docfx/files/3646270/docfx-percent-naming-bug.zip).

**Comment by mrEDitor** [comment] 2019-12-23 19:08
Hey, what is the point to close old issues? Neither stalebot, nor anyone else will fix it if it is closed.

**Comment by superyyrrzz** [comment] 2019-12-26 08:58
Sorry for late response... There must be some bug in the logic to fetch the file. You could try to work around this issue by changing the file name first.

**Comment by mrgopalakrishnan** [comment] 2021-06-11 09:52
The issue is while using System.Uri to convert absolute path to relative path. it can be fixed easily when we move to netstandard2.1 thanks to the new method System.IO.Path.GetRelativePath.

if we re not moving to netstandard2.1, we can do the fix in other ways.

**Comment by aguzev** [comment] 2022-05-06 19:44
> Now I have done a fix. but I cannot raise a pull request as I don't have access to the repository. Can anyone help me? how can i become a contributor to this project?

Does a pull request from a forked repo work for you?

**Comment by saipramod** [comment] 2024-02-14 23:48
@yufeih  Could you point me the pr for these fixes ? The issue is still happening with the version 2.75.2. This one is blocking the ADO wiki's. I will be happy to assist with a fix if one is needed.

**Closed** 2024-02-18 02:31 UTC
Labels: bug, help-wanted, static-site
