### ISSUE TITLE
source info doesn't work when key is undefined

### ISSUE THREAD

**Issue by OsmondJiang** [dotnet/docfx#4647] opened 2019-05-27 10:36 UTC
as title, even with `key` defined.

**Comment by OsmondJiang** [comment] 2019-05-27 11:26
we should ignore null value for writing, not reading.

**Comment by yufeih** [comment] 2019-05-28 01:48
That was intended, _nulls_ are preserved in `JToken` but are ignore nulls when converting to C# model, this is to ensure _null_ does not leak to C# model. What scenarios did you want it otherwise?

**Comment by OsmondJiang** [comment] 2019-05-28 03:06
We just want know the line info if user write a null value.

**Comment by OsmondJiang** [comment] 2019-05-28 08:16
there is another problem, but not hurry problem. When covert a strong model with source info to JToken and covert them back, the source info will be lost. @yufeih

**Comment by yufeih** [comment] 2019-05-28 08:20
> there is another problem, but not hurry problem. When covert a strong model with source info to JToken and covert them back, the source info will be lost. @yufeih

This is intentionally not supported, in such case, the suggested solution is **instead of** _JSON_ --> _C#_ --> _JToken_ --> _do work_, **prefer** _JSON_ -->_JToken_ --> _do work_ --> _C#_

**Comment by OsmondJiang** [comment] 2019-05-29 07:19
SourceInfo also doesn't work for if the filed is SourceInfo<xxx> but not defined in input model. Check this PR for example: #4648 

cc @live1206  @yufeih  @herohua

**Comment by yufeih** [comment] 2020-07-15 06:56
This is resolved by manually fallback to parent source info.

**Closed by yufeih** 2020-07-15 06:56 UTC
Labels: future, v3
