### ISSUE TITLE
Msbuild failed Sdks\Microsoft.NET.Sdk\Sdk\Sdk.props" was not found.

### ISSUE THREAD

**Issue by cjaeckel** [dotnet/docfx#1907] opened 2017-07-24 13:01 UTC
**DocFX Version Used**: 
docfx 2.21.1.0

**Template used**: (`default` or `statictoc` or contain custom template)
default

**Steps to Reproduce**:

1. docfx init -q
2. mkdir src/MyProject
3. cd src/MyProject
4. dotnet new classlib --framework netcoreapp1.1
5. dotnet restore
6. dotnet build
```
MyProject -> D:\core-dev\docfx_project\src\MyProject\bin\Debug\netcoreapp1.1\MyProject.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)
```
7. cd ../..
8. docfx

**Expected Behavior**:
should build the api doc.

**Actual Behavior**:
```
D:\core-dev\docfx_project>docfx
[17-07-24 12:51:44.567]Info:Config file docfx.json found, start generating metadata...
[17-07-24 12:51:45.750]Warning:[MetadataCommand.ExtractMetadata]Workspace failed with: [Failure] Msbuild failed when processing the file 'D:\core-dev\docfx_project\src\MyProject\MyProject.csproj' with message: The i
mported project "d:\opt\docfx\Sdks\Microsoft.NET.Sdk\Sdk\Sdk.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.  D:\core-dev\docfx_project\src\MyPro
ject\MyProject.csproj
[17-07-24 12:51:45.848]Warning:[MetadataCommand.ExtractMetadata]Project 'D:\core-dev\docfx_project\src\MyProject\MyProject.csproj' does not contain any documents.
[17-07-24 12:51:46.304]Warning:[MetadataCommand.ExtractMetadata]No metadata is generated for MyProject.

...

Build succeeded with warning.
[17-07-24 12:51:47.861]Warning:[MetadataCommand.ExtractMetadata]Workspace failed with: [Failure] Msbuild failed when processing the file 'D:\core-dev\docfx_project\src\MyProject\MyProject.csproj' with message: The i
mported project "d:\opt\docfx\Sdks\Microsoft.NET.Sdk\Sdk\Sdk.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.  D:\core-dev\docfx_project\src\MyPro
ject\MyProject.csproj
[17-07-24 12:51:47.862]Warning:[MetadataCommand.ExtractMetadata]Project 'D:\core-dev\docfx_project\src\MyProject\MyProject.csproj' does not contain any documents.
[17-07-24 12:51:47.862]Warning:[MetadataCommand.ExtractMetadata]No metadata is generated for MyProject.
        3 Warning(s)
        0 Error(s)
```

**Comment by vicancy** [comment] 2017-07-27 02:31
duplicate with https://github.com/dotnet/docfx/issues/1752, the root cause is there is a gap between msbuild tool and .NET core SDK build, so you have to install Visual Studio 2017 (not Build Tools but the full VS) as current workaround

**Comment by vicancy** [comment] 2017-07-27 02:33
Close this one shamelessly as duplicate...

**Closed by vicancy** 2017-07-27 02:33 UTC
