### ISSUE TITLE
does not contain any documents, No metadata is generated

### ISSUE THREAD

**Issue by WeihanLi** [dotnet/docfx#4035] opened 2019-02-13 11:18 UTC
**DocFX Version Used**: 

`2.40.10`

**Template used**:

default

**Steps to Reproduce**:

1. `choco install docfx` (2.40.10)
2. download project from [Github](https://github.com/WeihanLi/WeihanLi.Npoi)
3. run `docfx .\docfx.json` in powershell on root dir

**Actual Behavior**:

```
Build succeeded with warning.
[19-02-13 11:16:40.035]Warning:[MetadataCommand.ExtractMetadata]Project 'C:\projects\sources\WeihanLi.Npoi\src\WeihanLi.Npoi\WeihanLi.Npoi.csproj' does not contain any documents.
[19-02-13 11:16:40.036]Warning:[MetadataCommand.ExtractMetadata]No metadata is generated for WeihanLi.Npoi.
        2 Warning(s)
        0 Error(s)
```

**Comment by Kavignon** [comment] 2019-02-13 16:15
I have a similar issue! I'm able to generate the intermediate files (*.yml) but no HTML is generated in my _site folder...

**Comment by superyyrrzz** [comment] 2019-02-15 02:58
Hi @WeihanLi , I have created a PR to fix this: https://github.com/WeihanLi/WeihanLi.Npoi/pull/12 I still cannot find out the root cause why do document is found in the project. I work around this by generating metadata direclty from `*.cs`.

@Kavignon Your issue should be different from this. You have YAML generated, while this issue not. Please make sure to include the generated YAML files in the  `build.content` section.

**Comment by WeihanLi** [comment] 2019-02-15 03:04
@superyyrrzz  Thank you so much

**Comment by Kavignon** [comment] 2019-02-15 18:17
@superyyrrzz I used the configuration file that comes with the NuGet. And it was mentioned: 

```
  "build": {
    "content": [
      {
        "files": [
          "api/**.yml"
        ],
```

**Comment by superyyrrzz** [comment] 2019-02-16 16:24
@Kavignon The config looks good. You can create another issue with more detailed steps to help reproduce this issue. I will first close this one.

**Closed by superyyrrzz** 2019-02-16 16:24 UTC
