### ISSUE TITLE
[Bug] .NET API / Markdown: Unresolved `cref / xref` tags from `<summary>` in generated markdown.

### ISSUE THREAD

**Issue by Delsin-Yu** [dotnet/docfx#9879] opened 2024-04-19 08:22 UTC
## Describe the bug
The [following XML Documentation:](https://github.com/Delsin-Yu/GDViews.VirtualGridView/blob/main/GDViews.VirtualGridView/Factories/FactoryImpls.cs#L9)
![image](https://github.com/dotnet/docfx/assets/71481700/67330a18-0301-4811-b897-f35fb619d466)

does not resolve when converted to markdown, this is what [appears in](https://github.com/Delsin-Yu/GDViews.VirtualGridView/blob/main/Documentation/GodotViews.VirtualGrid.md) [the GitHub.](https://github.com/Delsin-Yu/GDViews.VirtualGridView/blob/main/Documentation/GodotViews.VirtualGrid.VirtualGridView.md)
![image](https://github.com/dotnet/docfx/assets/71481700/0ad4da2d-698e-4c0a-ab21-e2dda25069a4)
![image](https://github.com/dotnet/docfx/assets/71481700/383d1347-4926-473e-8310-a5e677a9ef68)

In contrast, the generated website appears to resolve the links correctly:
![image](https://github.com/dotnet/docfx/assets/71481700/27c47076-59fc-4944-95aa-89d04c6ffb74)
![image](https://github.com/dotnet/docfx/assets/71481700/3699cee5-4ccf-4479-ba0e-619724ce8fd3)

## Docfx.json

- `docfx.json` config

```json
{
	"rules": {
		"InvalidHref": "error"
	},
	"metadata": [
		{
			"src": [
				{
					"src": "GDViews.VirtualGridView",
					"files": [
						"**/*.csproj"
					]
				}
			],
			"dest": "Documentation",
			"filter": "filterConfig.yml",
			"outputFormat": "markdown",
			"disableGitFeatures": "true",
			"enumSortOrder": "declaringOrder"
		}
	]
}
```

## Source Repo

The [GDViews.VirtualGridView](https://github.com/Delsin-Yu/GDViews.VirtualGridView) repo.

**Comment by filzrev** [comment] 2024-04-19 09:29
> does not resolve when converted to markdown, this is what [appears in](https://github.com/Delsin-Yu/GDViews.VirtualGridView/blob/main/Documentation/GodotViews.VirtualGrid.md) [the GitHub.](https://github.com/Delsin-Yu/GDViews.VirtualGridView/blob/main/Documentation/GodotViews.VirtualGrid.VirtualGridView.md)

Currently generated markdown files with `"outputFormat": "markdown"` option are intended to be used as `docfx build` command inputs.

So generated markdown files contains some docfx specific custom tags like `<xref>`.
And these custom tags are ignored by GitHub's markdown preview.

**`Raw` view of generated file**
https://raw.githubusercontent.com/Delsin-Yu/GDViews.VirtualGridView/main/Documentation/GodotViews.VirtualGrid.md

---

If there are no strict requirements for previewing the markdown file on GitHub.
Try to [publish document to GitHub Pages](https://dotnet.github.io/docfx/#publish-to-github-pages)

**Comment by filzrev** [comment] 2024-04-19 23:54
@Kevinf63
It seems `xref` is not resolved as expected on official docs.  
 (it's resolved by `xrefService` before but it's retired #9659)

I've created PR(#9880) to resolve xref resolver issue on conceptual documentation.

**Comment by filzrev** [comment] 2024-04-26 05:40
It seems resolved by publishing docs to [GitHub pages](https://delsin-yu.github.io/GDViews.VirtualGridView/).
And official docs xref problems are resolved by merged PR.

@Delsin-Yu
If there is no additional problems. Please close this issue.

**Closed** 2024-04-26 06:53 UTC
Labels: bug, dotnet

**Comment by Delsin-Yu** [comment] 2024-04-26 06:55
There is a following issue when talking about resolving xrefs,, should I open a separate issue on it? Since it's not markdown-related.
![image](https://github.com/dotnet/docfx/assets/71481700/b8a0fbef-13ee-4a2c-b64c-2e3b7d1ee494)
https://delsin-yu.github.io/GDViews.VirtualGridView/api/GodotViews.VirtualGrid.DynamicGridViewers.html

**Comment by filzrev** [comment] 2024-04-26 07:44
> There is a following issue when talking about resolving xrefs.

It seems be caused by #9677 issue.
