### ISSUE TITLE
Support Code Wiki in Visual Studio Online (Markdown File Export)

### ISSUE THREAD

**Issue by SebGX** [dotnet/docfx#4334] opened 2019-04-09 09:23 UTC
**Operation System**: All

**DocFX Version Used**: 2.4.1

**Template used**: default

**Steps to Reproduce**:

1. Run DocFX as directed.

**Expected Behavior**:
Generate markdown files for use with Visual Studio Online's code wiki.

**Actual Behavior**:
A static HTML site. DocFX is unique among popular documentation tools for its lack of support for markdown generation.

**Comment by KalleOlaviNiemitalo** [comment] 2019-04-09 17:02
Duplicate of #684?

**Comment by superyyrrzz** [comment] 2019-07-03 08:36
close for dup

**Closed by superyyrrzz** 2019-07-03 08:36 UTC
