### ISSUE TITLE
[Bug] DotnetApiCatalog.GenerateManagedReferenceYamlFiles() hangs indefinitely on 2.76.0

### ISSUE THREAD

**Issue by jwfx** [dotnet/docfx#9988] opened 2024-06-05 14:31 UTC
**Describe the bug**
Calling `DotnetApiCatalog.GenerateManagedReferenceYamlFiles()` from a C# application works when when referencing Docfx.App 2.75.3 but hangs indefinitely after restoring when updating to 2.76.0

**To Reproduce**
1. Clone https://github.com/jwfx/DocFxHangRepro
2. `dotnet run` in `DocFxHangRepro` console app folder

**Expected behavior**
`GenerateManagedReferenceYamlFiles()` should not hang.

**Context (please complete the following information):**
- OS: Windows 10 x64
- Docfx version: 2.76.0
- .NET SDK 8.0.300

**Comment by filzrev** [comment] 2024-06-06 00:09
It seems that issue caused by `BuildHost` related `contentFiles` (that introduced at Roslyn 4.9.2) are not copied to bin directories when using `Docfx.App` package.

As a workaround. 
Add following package dependencies to `DocFxHangRepro.csproj`.
```
<PackageReference Include="Microsoft.CodeAnalysis.Workspaces.MSBuild" Version="4.9.2" />
<PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="4.9.2" />
```
By adding these settings.  related `contentFiles` are copied to bin directory.

I'll update following docs later.
https://dotnet.github.io/docfx/index.html#use-the-nuget-library

**Comment by jwfx** [comment] 2024-06-06 14:19
Thank you for your swift response.

The workaround does the trick.

**Comment by filzrev** [comment] 2024-07-01 03:22
@yufeih 
Please close this issue.
Because related document is updated by #9944.

**Closed** 2024-07-01 11:25 UTC
Labels: bug
