### ISSUE TITLE
Generate documentation from nuget packages not project reference

### ISSUE THREAD

**Issue by tomasz-lisowski-onxg** [dotnet/docfx#7520] opened 2021-08-11 11:37 UTC
Hi, it is possible to generate documentation from project witch is add as a nuget package reference?
When project is added a simple project reference (many project in solutions) everything is ok and documents are generated.

is there a solution for this problem via C# , .net core ?

**Comment by Afanyiyu** [comment] 2021-09-13 03:22
Maybe duplicate of #2635

**Comment by mikernet** [comment] 2021-10-20 07:59
Is there a reason you can't generate docs for the other project and then reference those from the current project? Once the docs for the nuget project are posted, you use `"xref"` in `docfx.json` to point to the `xrefmap.yml` file in the root and it will map links to those references.

**Closed** 2022-12-15 06:04 UTC
Labels: dotnet, duplicate
