### ISSUE TITLE
website view on iPad is overlayed when Hide Table of Contents is pressed, readability compromised!

### ISSUE THREAD

**Issue by anrenz** [dotnet/docfx#3362] opened 2018-09-03 08:09 UTC
**DocFX Version Used**: 2.24.0.892

**Template used**: contain custom template

**Steps to Reproduce**:

1. open generated website
2. on mobile devices (iPad for example) press Hide Table of Contents
3. look at the view of the website with hidden Table of Contents

**Expected Behavior**: Content like Title, text and images should be readable

**Actual Behavior**: Overlay compromises readability

**Comment by superyyrrzz** [comment] 2019-04-17 09:46
I do not see overlay:

![image](https://user-images.githubusercontent.com/3831744/56278396-bbe63580-6138-11e9-835c-ef57f297a2e3.png)


maybe duplicate of #4378

**Closed by superyyrrzz** 2019-04-17 09:46 UTC
Labels: Area-Template, bug, help-wanted
