### ISSUE TITLE
System.ArgumentNullException: Value cannot be null.

### ISSUE THREAD

**Issue by mezzo9** [dotnet/docfx#3989] opened 2019-01-30 00:04 UTC
**DocFX Version Used**: 
Lastest branch: dev, master, stable

**Template used**: (`default` or `statictoc` or contain custom template)
default
**Steps to Reproduce**:

1. pull the latest code
2. build
3. run docfx to generate documentation

**Expected Behavior**:
it should work fine. 

**Actual Behavior**:
Build completes successfully, and all the tests pass.
but I get below error.
**with the same exact configuration,If I download latest already build version, works just fine.**
```

System.ArgumentNullException: Value cannot be null.
Parameter name: key
   at System.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
   at System.Collections.Generic.Dictionary`2.ContainsKey(TKey key)
   at Microsoft.DocAsCode.Metadata.ManagedReference.MergeCommentsHelper.GetAllItemByCommentId(Dictionary`2 items, MetadataItem item) in C:\Repos\docfx\src\Microsoft.DocAsCode.Metadata.ManagedReference\MergeComments\MergeCommentsHelper.cs:line 101
   at Microsoft.DocAsCode.Metadata.ManagedReference.MergeCommentsHelper.PatchMetadataItem(MetadataItem assembly, IEnumerable`1 list) in C:\Repos\docfx\src\Microsoft.DocAsCode.Metadata.ManagedReference\MergeComments\MergeCommentsHelper.cs:line 87
   at Microsoft.DocAsCode.Metadata.ManagedReference.MergeCommentsHelper.MergeComments(MetadataItem item, IEnumerable`1 commentFiles) in C:\Repos\docfx\src\Microsoft.DocAsCode.Metadata.ManagedReference\MergeComments\MergeCommentsHelper.cs:line 30
   at Microsoft.DocAsCode.Metadata.ManagedReference.ExtractMetadataWorker.<SaveAllMembersFromCacheAsync>d__13.MoveNext() in C:\Repos\docfx\src\Microsoft.DocAsCode.Metadata.ManagedReference\ExtractMetadataWorker.cs:line 368
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.DocAsCode.Metadata.ManagedReference.ExtractMetadataWorker.<ExtractMetadataAsync>d__11.MoveNext() in C:\Repos\docfx\src\Microsoft.DocAsCode.Metadata.ManagedReference\ExtractMetadataWorker.cs:line 110
```

**Comment by superyyrrzz** [comment] 2019-01-30 09:24
Duplicate of #3979

**Closed by superyyrrzz** 2019-01-30 09:24 UTC
