### ISSUE TITLE
configuration migration failed for PR build

### ISSUE THREAD

**Issue by OsmondJiang** [dotnet/docfx#4026] opened 2019-02-13 05:14 UTC
https://github.com/OPS-E2E-PPE/E2E_DocFxV3/pull/87

**Comment by OsmondJiang** [comment] 2019-02-13 05:46
![image](https://user-images.githubusercontent.com/19990166/52689635-c26bfb80-2f95-11e9-8e34-abf0328ff191.png)

**Comment by OsmondJiang** [comment] 2019-02-13 07:02
@mingwli

**Comment by mingwli** [comment] 2019-02-27 06:11
The root cause was using '\~' for dependency repos. Check the test below, it used '\~/dependency/path' to use a dependency repo's article as token. '~' was resolved as docset root by resolveAlias config and docfx failed to locate the file.  The content was fixed in [this commit](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commit/e4ea6d45f11dadc88280e2ef3d23fb6cd8e1b4be#diff-6dddeff5f1576a7d85b6cdd180df07a7).

Resolve Alias migrator PR: 
https://ceapex.visualstudio.com/Engineering/_git/Docs.DocFX.MigrationTool/pullrequest/8534?_a=overview

**Closed by mingwli** 2019-02-27 06:11 UTC
Labels: v3
